using System.Threading.Channels;
using System.Text.Json.Serialization;
using System.Text.Json;
using System.Text.Encodings.Web;
using System.Text.Unicode;
using System.Numerics;
using System.Buffers.Binary;
using System.Buffers.Text;
using System.IO.Pipelines;
using System.Runtime.InteropServices;
using System.IO.MemoryMappedFiles;
using System.Threading;
using System.IO.Pipes;
using System.IO;
using System.Diagnostics.PerformanceData;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Dynamic;
using System.Security.Cryptography.X509Certificates;
using System.Security.Cryptography;
using System.Security;
using Microsoft.Win32.SafeHandles;
using System.Linq;
using System.Diagnostics.Eventing.Reader;
using System.Management.Instrumentation;
using System.Diagnostics.Eventing;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Buffers;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Schema;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json;
using Microsoft.Extensions.Primitives;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Configuration.Memory;
using Microsoft.Extensions.Configuration;
using System.Threading.Tasks.Sources;
using System.Threading.Tasks;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.SignalR.Protocol;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Features.Authentication;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Connections;
using Microsoft.AspNetCore.Http.Connections.Client;
using Microsoft.AspNetCore.Connections.Features;
using Microsoft.AspNetCore.Connections;
using Microsoft.Xml.Serialization.GeneratedAssembly;
using DoorsAddoOnLibrary.Models;
using DoorsAddoOnLibrary.BillOfMaterialsComponents;
using DoorsAddoOnLibrary.LoginManager;
using DoorsAddoOnLibrary.TbServices;
using DoorsAddoOnLibrary;
using DevExpress.XtraTreeList.Printing;
using DevExpress.XtraTreeList.ViewInfo;
using DevExpress.XtraTreeList.Menu;
using DevExpress.XtraTreeList.Helpers;
using DevExpress.XtraTreeList.Handler;
using DevExpress.XtraTreeList.Painter;
using DevExpress.XtraTreeList.Data;
using DevExpress.XtraTreeList.StyleFormatConditions;
using DevExpress.XtraTreeList.Scrolling;
using DevExpress.XtraTreeList.Frames;
using DevExpress.XtraTreeList.Design;
using DevExpress.XtraTreeList.Localization;
using DevExpress.XtraTreeList.Internal;
using DevExpress.XtraTreeList.Columns;
using DevExpress.XtraTreeList.FilterEditor;
using DevExpress.XtraTreeList.Nodes.Operations;
using DevExpress.XtraTreeList.Native;
using DevExpress.XtraTreeList.Nodes;
using DevExpress.XtraTreeList.Dragging;
using DevExpress.XtraTreeList.Accessibility;
using DevExpress.XtraTreeList.Blending;
using DevExpress.XtraTreeList;
using DevExpress.XtraLayout.Tab;
using DevExpress.XtraLayout.Scrolling;
using DevExpress.XtraLayout.Registrator;
using DevExpress.XtraLayout.Localization;
using DevExpress.XtraLayout.Converter;
using DevExpress.XtraLayout.Printing;
using DevExpress.XtraLayout.Dragging;
using DevExpress.XtraLayout.Diagnostics;
using DevExpress.XtraDataLayout;
using DevExpress.XtraLayout.Helpers;
using DevExpress.XtraDashboardLayout;
using DevExpress.XtraLayout.Customization.Controls;
using DevExpress.XtraLayout.Utils;
using DevExpress.XtraLayout.Accessibility;
using DevExpress.XtraLayout.ViewInfo;
using DevExpress.XtraLayout.Painting;
using DevExpress.XtraLayout.HitInfo;
using DevExpress.XtraLayout.Customization;
using DevExpress.XtraLayout.Resizing;
using DevExpress.XtraLayout;
using DevExpress.XtraLayout.Handlers;
using DevExpress.XtraLayout.Adapters;
using DevExpress.XtraGrid.Repository;
using DevExpress.XtraGrid.Tab;
using DevExpress.XtraGrid.Filter.Parser;
using DevExpress.XtraGrid.Menu;
using DevExpress.XtraGrid.Filter;
using DevExpress.XtraGrid.Printing;
using DevExpress.XtraGrid.Editors;
using DevExpress.XtraGrid.Frames;
using DevExpress.XtraGrid.Registrator;
using DevExpress.XtraGrid.Views.Layout.Printing;
using DevExpress.XtraGrid.Views.Layout.Drawing;
using DevExpress.XtraGrid.Views.Layout.Modes;
using DevExpress.XtraGrid.Views.Layout.Customization;
using DevExpress.XtraGrid.Views.Layout.Events;
using DevExpress.XtraGrid.Views.Layout.ViewInfo;
using DevExpress.XtraGrid.Views.Layout.Frames;
using DevExpress.XtraGrid.Views.Layout.Handler;
using DevExpress.XtraGrid.Views.Layout.Designer;
using DevExpress.XtraGrid.Views.Layout;
using DevExpress.XtraGrid.GroupSummaryEditor;
using DevExpress.XtraGrid.Localization;
using DevExpress.XtraGrid.Drawing;
using DevExpress.XtraGrid.Internal;
using DevExpress.XtraGrid.FilterEditor;
using DevExpress.XtraGrid.Export;
using DevExpress.XtraGrid.Views.Card.ViewInfo;
using DevExpress.XtraGrid.Views.Card.Drawing;
using DevExpress.XtraGrid.Views.Card.Handler;
using DevExpress.XtraGrid.Views.Card;
using DevExpress.XtraGrid.Design;
using DevExpress.XtraGrid.Blending;
using DevExpress.XtraGrid.Helpers;
using DevExpress.XtraGrid.Controls;
using DevExpress.XtraGrid.Views.Printing;
using DevExpress.XtraGrid.Scrolling;
using DevExpress.XtraGrid.Accessibility;
using DevExpress.XtraGrid.Views.BandedGrid.Customization;
using DevExpress.XtraGrid.Views.Grid.Customization;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Skins;
using DevExpress.XtraGrid.Views.BandedGrid.ViewInfo;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using DevExpress.XtraGrid.Views.Base.ViewInfo;
using DevExpress.XtraGrid.Views.BandedGrid.Drawing;
using DevExpress.XtraGrid.Views.Grid.Drawing;
using DevExpress.XtraGrid.Views.BandedGrid;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.Base.Handler;
using DevExpress.XtraGrid.Views.Grid.Handler;
using DevExpress.XtraGrid.Views.BandedGrid.Handler;
using DevExpress.XtraGrid.Dragging;
using DevExpress.XtraEditors.FeatureBrowser;
using DevExpress.XtraTab.Buttons;
using DevExpress.XtraTab.Registrator;
using DevExpress.XtraTab.Drawing;
using DevExpress.XtraTab.ViewInfo;
using DevExpress.Accessibility.Tab;
using DevExpress.XtraWaitForm;
using DevExpress.XtraSplashForm;
using DevExpress.XtraSplashScreen;
using DevExpress.XtraEditors.Registrator;
using DevExpress.XtraEditors.Internal;
using DevExpress.XtraPivotGrid;
using DevExpress.XtraTab;
using DevExpress.XtraEditors.ColorPickEditControl;
using DevExpress.XtraEditors.Calendar;
using DevExpress.XtraEditors.NavigatorButtons;
using DevExpress.XtraEditors.Mask;
using DevExpress.XtraEditors.Popup;
using DevExpress.XtraEditors.Helpers;
using DevExpress.XtraBars.Docking;
using DevExpress.XtraEditors.Design;
using DevExpress.XtraEditors.Frames;
using DevExpress.XtraEditors.Customization;
using DevExpress.XtraEditors.ListControls;
using DevExpress.XtraEditors.Container;
using DevExpress.XtraEditors.CodedUISupport;
using DevExpress.XtraBars.Docking2010;
using DevExpress.XtraEditors.ButtonPanel;
using DevExpress.XtraEditors.Senders;
using DevExpress.XtraEditors.Persistent;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraBars.Alerter;
using DevExpress.Utils.Frames;
using DevExpress.Utils.WXPaint;
using DevExpress.Utils.Mdi;
using DevExpress.Utils.Registrator;
using DevExpress.Utils.Native;
using DevExpress.Skins.Info;
using DevExpress.Skins.XtraForm;
using DevExpress.UserSkins;
using DevExpress.XtraReports.Serialization;
using DevExpress.XtraEditors.ViewInfo;
using DevExpress.Utils.NonclientArea;
using DevExpress.Utils.Drawing.Helpers;
using DevExpress.Utils.Helpers;
using DevExpress.Utils.Paint;
using DevExpress.LookAndFeel.Design;
using DevExpress.LookAndFeel.Helpers;
using DevExpress.Utils.Win.Hook;
using DevExpress.Utils.ViewInfo;
using DevExpress.Utils.ToolTip.ViewInfo;
using DevExpress.Utils.Extensions;
using DevExpress.XtraEditors.ScrollHelpers;
using DevExpress.Utils.Win;
using DevExpress.Utils.DragDrop;
using DevExpress.Skins;
using DevExpress.Utils.Gesture;
using DevExpress.Utils.Compress;
using DevExpress.Utils.CodedUISupport;
using DevExpress.Utils.Drawing;
using DevExpress.Utils.Drawing.Animation;
using DevExpress.Accessibility;
using DevExpress.LookAndFeel;
using DevExpress.XtraEditors.Drawing;
using DevExpress.Printing.ServiceModel.DataContracts;
using DevExpress.Xpf.Printing.ServiceModel.DataContracts;
using DevExpress.XtraReports.ServiceModel.DataContracts;
using DevExpress.XtraPrinting.Drawing;
using DevExpress.XtraPrinting.Preview;
using DevExpress.Printing;
using DevExpress.XtraReports;
using DevExpress.XtraPrinting.InternalAccess;
using DevExpress.XtraPrinting.Export.Pdf.Compression;
using System.Collections;
using DevExpress.XtraPrinting.Native.LayoutAdjustment;
using DevExpress.XtraPrinting.Native.TextRotation;
using DevExpress.XtraPrinting.Native.Navigation;
using DevExpress.XtraPrinting.Native.Lines;
using DevExpress.XtraPrinting.HtmlExport;
using DevExpress.XtraPrinting.HtmlExport.Native;
using DevExpress.XtraPrinting.Export.XLS;
using DevExpress.XtraPrinting.Export.Text;
using DevExpress.XtraPrinting.Export.Rtf;
using DevExpress.XtraPrinting.Export.Imaging;
using DevExpress.XtraPrinting.Native.ExportOtions;
using DevExpress.XtraPrinting.Native.ExportOptionsControllers;
using DevExpress.XtraPrinting.Shape;
using DevExpress.XtraPrinting.Shape.Native;
using DevExpress.XtraPrinting.NativeBricks;
using DevExpress.XtraPrinting.Export.Pdf;
using DevExpress.XtraPrinting.Export;
using DevExpress.Printing.Core.Native;
using DevExpress.Printing.Core;
using DevExpress.XtraPrintingLinks;
using DevExpress.Printing.Core.HtmlExport;
using DevExpress.XtraPrinting.Export.Web;
using DevExpress.XtraPrinting.HtmlExport.Controls;
using DevExpress.XtraPrinting.BarCode.Native;
using DevExpress.XtraPrinting.BarCode;
using DevExpress.XtraPrinting.BrickExporters;
using DevExpress.Data.XtraReports.Wizard.Views;
using DevExpress.Data.XtraReports.Wizard.Presenters;
using DevExpress.Utils.Implementation;
using DevExpress.Data.Summary;
using DevExpress.Data.Async.Helpers;
using DevExpress.Schedule.Serializing;
using DevExpress.Schedule;
using DevExpress.Utils.Text.Internal;
using DevExpress.Data.Async;
using DevExpress.Data.Printing.Native;
using DevExpress.Utils.Zip;
using DevExpress.XtraPrinting.Localization;
using DevExpress.XtraPrinting.DataNodes;
using DevExpress.Data.ChartDataSources;
using DevExpress.Charts.Native;
using DevExpress.Xpo.Logger.Transport;
using DevExpress.Xpo.Logger;
using DevExpress.Utils.Text;
using DevExpress.XtraEditors.Filtering;
using DevExpress.XtraEditors;
using DevExpress.Data.ExpressionEditor;
using DevExpress.XtraExport;
using DevExpress.Data.Linq.Helpers;
using DevExpress.Data.Linq;
using DevExpress.Utils.Internal;
using DevExpress.Xpo.Providers;
using DevExpress.Data.Db;
using DevExpress.Data.Design;
using DevExpress.Xpo.XtraData;
using DevExpress.Data.Utils.ServiceModel.Native;
using DevExpress.CodeParser;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.DXErrorProvider;
using DevExpress.XtraPrinting;
using DevExpress.Internal;
using DevExpress.XtraPrinting.Design;
using DevExpress.Utils.Serializing.Helpers;
using DevExpress.Utils.Editors;
using DevExpress.Utils.Localization.Internal;
using DevExpress.Utils.Localization;
using DevExpress.Data.Utils;
using DevExpress.Utils.Serializing;
using DevExpress.WebUtils;
using DevExpress.Utils.Controls;
using DevExpress.Data.IO;
using DevExpress.XtraSpellChecker.Native;
using DevExpress.XtraSpellChecker.Parser;
using DevExpress.XtraSpellChecker;
using DevExpress.Services.Implementation;
using DevExpress.Services;
using DevExpress.XtraRichEdit.Export.Rtf;
using DevExpress.Data.Mask;
using DevExpress.Utils.KeyboardHandler;
using DevExpress.Utils.Design;
using DevExpress.Data.XtraReports.Wizard.Native;
using DevExpress.Data.XtraReports.Wizard;
using DevExpress.Data.XtraReports.ServiceModel.DataContracts;
using DevExpress.Data.XtraReports.ServiceModel;
using DevExpress.XtraReports.Parameters;
using DevExpress.Data.XtraReports.Native;
using DevExpress.Data.XtraReports.Labels;
using DevExpress.Data.XtraReports.DataProviders;
using DevExpress.XtraReports.Design.Commands;
using DevExpress.XtraReports.UserDesigner;
using DevExpress.XtraReports.Native.Parameters;
using DevExpress.XtraReports.UI;
using DevExpress.Data.WizardFramework;
using DevExpress.Utils.About;
using DevExpress.Data.Utils.ServiceModel;
using DevExpress.Utils.IoC;
using DevExpress.Xpf.Printing;
using DevExpress.XtraPrinting.Native;
using DevExpress.Utils.OAuth.Provider;
using DevExpress.Utils.OAuth;
using DevExpress.Utils.Gac;
using DevExpress.XtraGrid;
using DevExpress.Data.Filtering.Exceptions;
using DevExpress.Xpo;
using DevExpress.Utils.Extensions.Helpers;
using DevExpress.Data.Details;
using DevExpress.Xpo.Exceptions;
using DevExpress.Xpo.DB.Exceptions;
using DevExpress.Xpo.Helpers;
using DevExpress.Xpo.DB;
using DevExpress.Xpo.DB.Helpers;
using DevExpress.Data.Storage;
using DevExpress.Data.Access;
using DevExpress.Utils.Menu;
using DevExpress.Utils.Commands;
using DevExpress.Data.Filtering;
using DevExpress.Data.Helpers;
using DevExpress.Data.Selection;
using DevExpress.XtraReports.Native;
using DevExpress.XtraReports.Native.Data;
using DevExpress.Data.Browsing.Design;
using DevExpress.XtraReports.Design;
using DevExpress.Data;
using DevExpress.Services.Internal;
using DevExpress.Data.Browsing;
using DevExpress.Data.Filtering.Helpers;
using DevExpress.Data.Native;
using DevExpress.Utils;
using Microarea.Library.WCFGeneratedFunctions;
using System.Collections.Generic;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.OleDb;
using Microarea.EasyBuilder;
using Microarea.EasyBuilder.MVC;
using Microarea.TaskBuilderNet.UI.WinControls;
using Microarea.TaskBuilderNet.Interfaces.View;
using Microarea.TaskBuilderNet.Interfaces;
using Microarea.TaskBuilderNet.Core.CoreTypes;
using Microarea.TaskBuilderNet.Core.EasyBuilder;
using Microarea.TaskBuilderNet.Core.Generic;
using Microarea.Framework.TBApplicationWrapper;
using Microarea.TaskBuilderNet.Interfaces.Model;
using System.ComponentModel;
using System.Windows.Forms;
using System.Xml;
using System.Drawing;
using System.Data;
using System;
namespace Customization.Doors.Doors.DynamicDocuments.TabelleLarghezzePannello.TabelleLarghezzePannello
{
	public class BEDBTDOORSTabellaPannelliR : Microarea.Framework.TBApplicationWrapper.MBodyEdit
	{
		public BEDBTDOORSTabellaPannelliR(Microarea.TaskBuilderNet.Interfaces.View.IWindowWrapperContainer parentWindow, string controlName, string controlClass, System.Drawing.Point location, bool hasCodeBehind) : base(parentWindow, controlName, controlClass, location, hasCodeBehind)
		{
		}

		[Microarea.TaskBuilderNet.Core.EasyBuilder.PreserveFieldAttribute]
		public new MDTabelleLarghezzePannello Document
		{
			get
			{
				return (MDTabelleLarghezzePannello)DocumentController.controller.Document;
			}
		}

		public MBodyEditColumn col_Finitura;

		public MBodyEditColumn col_Battuta;

		public MBodyEditColumn col_Dimensione;

		public MBodyEditColumn col_DaCm;

		public MBodyEditColumn col_ACm;

		public MBodyEditColumn col_CmInternoBattutaPannello;

		public MBodyEditColumn col_BattutaComponente;

		public MBodyEditColumn col_IsStandard;

		public MBodyEditColumn col_Operation1;

		public MBodyEditColumn col_Operation2;

		public MBodyEditColumn col_Operation3;

		public override void CreateComponents()
		{
			col_Finitura = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Finitura", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_Finitura.DataBinding = new FieldDataBinding(Document.DBTDOORSTabellaPannelliR.TTAG_DOORS_TabellaPannelliR.fld_Finitura, Document.DBTDOORSTabellaPannelliR);
			col_Finitura.AddChangedProperty("DataBinding");
			col_Finitura.ColPos = 0;
			col_Finitura.AddChangedProperty("ColPos");
			col_Finitura.SizeInChars = new System.Drawing.Size(8, 1);
			col_Finitura.AddChangedProperty("SizeInChars");
			col_Finitura.TitleTextColor = System.Drawing.Color.Black;
			col_Finitura.AddChangedProperty("TitleTextColor");
			col_Finitura.TitleBackColor = System.Drawing.Color.Transparent;
			col_Finitura.AddChangedProperty("TitleBackColor");
			col_Finitura.Visible = false;
			col_Finitura.AddChangedProperty("Visible");
			col_Finitura.AddChangedProperty("ColumnTitle");
			this.Add(col_Finitura, false);
			col_Battuta = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Battuta", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_Battuta.DataBinding = new FieldDataBinding(Document.DBTDOORSTabellaPannelliR.TTAG_DOORS_TabellaPannelliR.fld_Battuta, Document.DBTDOORSTabellaPannelliR);
			col_Battuta.AddChangedProperty("DataBinding");
			col_Battuta.ColPos = 1;
			col_Battuta.AddChangedProperty("ColPos");
			col_Battuta.SizeInChars = new System.Drawing.Size(8, 1);
			col_Battuta.AddChangedProperty("SizeInChars");
			col_Battuta.TitleTextColor = System.Drawing.Color.Black;
			col_Battuta.AddChangedProperty("TitleTextColor");
			col_Battuta.TitleBackColor = System.Drawing.Color.Transparent;
			col_Battuta.AddChangedProperty("TitleBackColor");
			col_Battuta.Visible = false;
			col_Battuta.AddChangedProperty("Visible");
			col_Battuta.AddChangedProperty("ColumnTitle");
			this.Add(col_Battuta, false);
			col_Dimensione = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Dimensione", "EnumCombo", new System.Drawing.Point(0, 0), false);
			col_Dimensione.DataBinding = new FieldDataBinding(Document.DBTDOORSTabellaPannelliR.TTAG_DOORS_TabellaPannelliR.fld_Dimensione, Document.DBTDOORSTabellaPannelliR);
			col_Dimensione.AddChangedProperty("DataBinding");
			col_Dimensione.ColPos = 2;
			col_Dimensione.AddChangedProperty("ColPos");
			col_Dimensione.SizeInChars = new System.Drawing.Size(1, 1);
			col_Dimensione.AddChangedProperty("SizeInChars");
			col_Dimensione.TitleTextColor = System.Drawing.Color.Black;
			col_Dimensione.AddChangedProperty("TitleTextColor");
			col_Dimensione.TitleBackColor = System.Drawing.Color.Transparent;
			col_Dimensione.AddChangedProperty("TitleBackColor");
			col_Dimensione.Visible = true;
			col_Dimensione.AddChangedProperty("Visible");
			col_Dimensione.AddChangedProperty("ColumnTitle");
			this.Add(col_Dimensione, true);
			col_DaCm = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "DaCm", "DoubleEdit", new System.Drawing.Point(0, 0), false);
			col_DaCm.DataBinding = new FieldDataBinding(Document.DBTDOORSTabellaPannelliR.TTAG_DOORS_TabellaPannelliR.fld_DaCm, Document.DBTDOORSTabellaPannelliR);
			col_DaCm.AddChangedProperty("DataBinding");
			col_DaCm.ColPos = 3;
			col_DaCm.AddChangedProperty("ColPos");
			col_DaCm.SizeInChars = new System.Drawing.Size(1, 1);
			col_DaCm.AddChangedProperty("SizeInChars");
			col_DaCm.TitleTextColor = System.Drawing.Color.Black;
			col_DaCm.AddChangedProperty("TitleTextColor");
			col_DaCm.TitleBackColor = System.Drawing.Color.Transparent;
			col_DaCm.AddChangedProperty("TitleBackColor");
			col_DaCm.Visible = true;
			col_DaCm.AddChangedProperty("Visible");
			col_DaCm.AddChangedProperty("ColumnTitle");
			this.Add(col_DaCm, false);
			col_ACm = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "ACm", "DoubleEdit", new System.Drawing.Point(0, 0), false);
			col_ACm.DataBinding = new FieldDataBinding(Document.DBTDOORSTabellaPannelliR.TTAG_DOORS_TabellaPannelliR.fld_ACm, Document.DBTDOORSTabellaPannelliR);
			col_ACm.AddChangedProperty("DataBinding");
			col_ACm.ColPos = 4;
			col_ACm.AddChangedProperty("ColPos");
			col_ACm.SizeInChars = new System.Drawing.Size(1, 1);
			col_ACm.AddChangedProperty("SizeInChars");
			col_ACm.TitleTextColor = System.Drawing.Color.Black;
			col_ACm.AddChangedProperty("TitleTextColor");
			col_ACm.TitleBackColor = System.Drawing.Color.Transparent;
			col_ACm.AddChangedProperty("TitleBackColor");
			col_ACm.Visible = true;
			col_ACm.AddChangedProperty("Visible");
			col_ACm.AddChangedProperty("ColumnTitle");
			this.Add(col_ACm, false);
			col_CmInternoBattutaPannello = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "CmInternoBattutaPannello", "DoubleEdit", new System.Drawing.Point(0, 0), false);
			col_CmInternoBattutaPannello.DataBinding = new FieldDataBinding(Document.DBTDOORSTabellaPannelliR.TTAG_DOORS_TabellaPannelliR.fld_CmInternoBattutaPannello, Document.DBTDOORSTabellaPannelliR);
			col_CmInternoBattutaPannello.AddChangedProperty("DataBinding");
			col_CmInternoBattutaPannello.ColPos = 5;
			col_CmInternoBattutaPannello.AddChangedProperty("ColPos");
			col_CmInternoBattutaPannello.SizeInChars = new System.Drawing.Size(1, 1);
			col_CmInternoBattutaPannello.AddChangedProperty("SizeInChars");
			col_CmInternoBattutaPannello.TitleTextColor = System.Drawing.Color.Black;
			col_CmInternoBattutaPannello.AddChangedProperty("TitleTextColor");
			col_CmInternoBattutaPannello.TitleBackColor = System.Drawing.Color.Transparent;
			col_CmInternoBattutaPannello.AddChangedProperty("TitleBackColor");
			col_CmInternoBattutaPannello.Visible = true;
			col_CmInternoBattutaPannello.AddChangedProperty("Visible");
			col_CmInternoBattutaPannello.AddChangedProperty("ColumnTitle");
			this.Add(col_CmInternoBattutaPannello, false);
			col_BattutaComponente = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "BattutaComponente", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_BattutaComponente.DataBinding = new FieldDataBinding(Document.DBTDOORSTabellaPannelliR.TTAG_DOORS_TabellaPannelliR.fld_BattutaComponente, Document.DBTDOORSTabellaPannelliR);
			col_BattutaComponente.AddChangedProperty("DataBinding");
			col_BattutaComponente.ColPos = 6;
			col_BattutaComponente.AddChangedProperty("ColPos");
			col_BattutaComponente.HotLink = Document.HKLDOORSBattuteHlRighe;
			col_BattutaComponente.AddChangedProperty("HotLink");
			col_BattutaComponente.SizeInChars = new System.Drawing.Size(8, 1);
			col_BattutaComponente.AddChangedProperty("SizeInChars");
			col_BattutaComponente.TitleTextColor = System.Drawing.Color.Black;
			col_BattutaComponente.AddChangedProperty("TitleTextColor");
			col_BattutaComponente.TitleBackColor = System.Drawing.Color.Transparent;
			col_BattutaComponente.AddChangedProperty("TitleBackColor");
			col_BattutaComponente.Visible = true;
			col_BattutaComponente.AddChangedProperty("Visible");
			col_BattutaComponente.AddChangedProperty("ColumnTitle");
			this.Add(col_BattutaComponente, true);
			col_IsStandard = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "IsStandard", "CheckBox", new System.Drawing.Point(0, 0), false);
			col_IsStandard.DataBinding = new FieldDataBinding(Document.DBTDOORSTabellaPannelliR.TTAG_DOORS_TabellaPannelliR.fld_IsStandard, Document.DBTDOORSTabellaPannelliR);
			col_IsStandard.AddChangedProperty("DataBinding");
			col_IsStandard.ColPos = 7;
			col_IsStandard.AddChangedProperty("ColPos");
			col_IsStandard.SizeInChars = new System.Drawing.Size(1, 1);
			col_IsStandard.AddChangedProperty("SizeInChars");
			col_IsStandard.TitleTextColor = System.Drawing.Color.Black;
			col_IsStandard.AddChangedProperty("TitleTextColor");
			col_IsStandard.TitleBackColor = System.Drawing.Color.Transparent;
			col_IsStandard.AddChangedProperty("TitleBackColor");
			col_IsStandard.Visible = true;
			col_IsStandard.AddChangedProperty("Visible");
			col_IsStandard.AddChangedProperty("ColumnTitle");
			this.Add(col_IsStandard, false);
			col_Operation1 = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Operation1", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_Operation1.DataBinding = new FieldDataBinding(Document.DBTDOORSTabellaPannelliR.TTAG_DOORS_TabellaPannelliR.fld_Operation1, Document.DBTDOORSTabellaPannelliR);
			col_Operation1.AddChangedProperty("DataBinding");
			col_Operation1.ColPos = 8;
			col_Operation1.AddChangedProperty("ColPos");
			col_Operation1.HotLink = Document.HKLOperations1;
			col_Operation1.AddChangedProperty("HotLink");
			col_Operation1.SizeInChars = new System.Drawing.Size(21, 1);
			col_Operation1.AddChangedProperty("SizeInChars");
			col_Operation1.TitleTextColor = System.Drawing.Color.Black;
			col_Operation1.AddChangedProperty("TitleTextColor");
			col_Operation1.TitleBackColor = System.Drawing.Color.Transparent;
			col_Operation1.AddChangedProperty("TitleBackColor");
			col_Operation1.Visible = true;
			col_Operation1.AddChangedProperty("Visible");
			col_Operation1.AddChangedProperty("ColumnTitle");
			this.Add(col_Operation1, false);
			col_Operation2 = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Operation2", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_Operation2.DataBinding = new FieldDataBinding(Document.DBTDOORSTabellaPannelliR.TTAG_DOORS_TabellaPannelliR.fld_Operation2, Document.DBTDOORSTabellaPannelliR);
			col_Operation2.AddChangedProperty("DataBinding");
			col_Operation2.ColPos = 9;
			col_Operation2.AddChangedProperty("ColPos");
			col_Operation2.HotLink = Document.HKLOperations2;
			col_Operation2.AddChangedProperty("HotLink");
			col_Operation2.SizeInChars = new System.Drawing.Size(21, 1);
			col_Operation2.AddChangedProperty("SizeInChars");
			col_Operation2.TitleTextColor = System.Drawing.Color.Black;
			col_Operation2.AddChangedProperty("TitleTextColor");
			col_Operation2.TitleBackColor = System.Drawing.Color.Transparent;
			col_Operation2.AddChangedProperty("TitleBackColor");
			col_Operation2.Visible = true;
			col_Operation2.AddChangedProperty("Visible");
			col_Operation2.AddChangedProperty("ColumnTitle");
			this.Add(col_Operation2, false);
			col_Operation3 = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Operation3", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_Operation3.DataBinding = new FieldDataBinding(Document.DBTDOORSTabellaPannelliR.TTAG_DOORS_TabellaPannelliR.fld_Operation3, Document.DBTDOORSTabellaPannelliR);
			col_Operation3.AddChangedProperty("DataBinding");
			col_Operation3.ColPos = 10;
			col_Operation3.AddChangedProperty("ColPos");
			col_Operation3.HotLink = Document.HKLOperations3;
			col_Operation3.AddChangedProperty("HotLink");
			col_Operation3.SizeInChars = new System.Drawing.Size(21, 1);
			col_Operation3.AddChangedProperty("SizeInChars");
			col_Operation3.TitleTextColor = System.Drawing.Color.Black;
			col_Operation3.AddChangedProperty("TitleTextColor");
			col_Operation3.TitleBackColor = System.Drawing.Color.Transparent;
			col_Operation3.AddChangedProperty("TitleBackColor");
			col_Operation3.Visible = true;
			col_Operation3.AddChangedProperty("Visible");
			col_Operation3.AddChangedProperty("ColumnTitle");
			this.Add(col_Operation3, false);
		}

		public override void ApplyResources()
		{
			Microarea.EasyBuilder.CustomizationComponentResourceManager resources = Strings.ResourceManager;
			resources.ApplyResources(col_Finitura, "col_Finitura");
			resources.ApplyResources(col_Battuta, "col_Battuta");
			resources.ApplyResources(col_Dimensione, "col_Dimensione");
			resources.ApplyResources(col_DaCm, "col_DaCm");
			resources.ApplyResources(col_ACm, "col_ACm");
			resources.ApplyResources(col_CmInternoBattutaPannello, "col_CmInternoBattutaPannello");
			resources.ApplyResources(col_BattutaComponente, "col_BattutaComponente");
			resources.ApplyResources(col_IsStandard, "col_IsStandard");
			resources.ApplyResources(col_Operation1, "col_Operation1");
			resources.ApplyResources(col_Operation2, "col_Operation2");
			resources.ApplyResources(col_Operation3, "col_Operation3");
		}

		public override void ClearComponents()
		{
			base.ClearComponents();
			col_Finitura = null;
			col_Battuta = null;
			col_Dimensione = null;
			col_DaCm = null;
			col_ACm = null;
			col_CmInternoBattutaPannello = null;
			col_BattutaComponente = null;
			col_IsStandard = null;
			col_Operation1 = null;
			col_Operation2 = null;
			col_Operation3 = null;
		}
	}
}
