CREATE TABLE "TAG_DOORS_CONFIGURAZIONIVAR" (
    "LINE" NUMBER (6) NOT NULL,
    "IDGUID" VARCHAR2 (50) NOT NULL,
    "CODVARIANTE" VARCHAR2 (21) NOT NULL,
    "BOM" VARCHAR2 (21) DEFAULT (''),
    CONSTRAINT "PK_TAG_DOORS_CONFIGURAZIONIVAR" PRIMARY KEY
    (
        "LINE",
        "IDGUID",
        "CODVARIANTE"
    )
)
GO
