CREATE TABLE "TAG_DOORS_TABELLAPANNELLIAP" (
    "FINITURA" VARCHAR2 (8) NOT NULL,
    "BATTUTA" VARCHAR2 (8) NOT NULL,
    "APERTURA" VARCHAR2 (12) NOT NULL,
    CONSTRAINT "PK_TAG_DOORS_TABELLAPANNELLIAP" PRIMARY KEY
    (
        "FINITURA",
        "BATTUTA",
        "APERTURA"
    )
)
GO
