ALTER TABLE "MA_ITEMS"
ADD "DOORSFINITURA" VARCHAR2 (8) DEFAULT ('')
GO


UPDATE "MA_ITEMS" SET "DOORSFINITURA" = '' WHERE "DOORSFINITURA" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSBATTUTA" VARCHAR2 (8) DEFAULT ('')
GO


UPDATE "MA_ITEMS" SET "DOORSBATTUTA" = '' WHERE "DOORSBATTUTA" IS NULL
GO


