using Wv2Edge;
using WinSCP;
using System.Threading.Channels;
using System.Text.Json.Serialization;
using System.Text.Json;
using System.Text.Encodings.Web;
using System.Text.Unicode;
using System.Numerics;
using System.Buffers.Binary;
using System.Buffers.Text;
using System.IO.Pipelines;
using System.Runtime.InteropServices;
using System.IO.MemoryMappedFiles;
using System.Threading;
using System.IO.Pipes;
using System.IO;
using System.Diagnostics.PerformanceData;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Dynamic;
using System.Security.Cryptography.X509Certificates;
using System.Security.Cryptography;
using System.Security;
using Microsoft.Win32.SafeHandles;
using System.Linq;
using System.Diagnostics.Eventing.Reader;
using System.Management.Instrumentation;
using System.Diagnostics.Eventing;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Buffers;
using RestSharp.Validation;
using RestSharp.Serializers;
using RestSharp.Contrib;
using RestSharp.Extensions;
using RestSharp.Deserializers;
using RestSharp.Authenticators.OAuth;
using RestSharp.Authenticators;
using RestSharp;
using Renci.SshNet.Common;
using Renci.SshNet.Compression;
using Renci.SshNet.Messages.Authentication;
using Renci.SshNet.Messages.Connection;
using Renci.SshNet.Messages.Transport;
using Renci.SshNet.Messages;
using Renci.SshNet.Security.Cryptography.Ciphers.Modes;
using Renci.SshNet.Security.Cryptography.Ciphers.Paddings;
using Renci.SshNet.Security.Cryptography.Ciphers;
using Renci.SshNet.Security.Cryptography;
using Renci.SshNet.Security;
using Renci.SshNet.Sftp;
using Renci.SshNet;
using OpenCartGateClasses;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Schema;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json;
using Microsoft.Web.WebView2.WinForms;
using Microsoft.Web.WebView2.Core.Raw;
using Microsoft.Web.WebView2.Core;
using Microsoft.Extensions.Primitives;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Configuration.Memory;
using Microsoft.Extensions.Configuration;
using System.Threading.Tasks.Sources;
using System.Threading.Tasks;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.SignalR.Protocol;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Features.Authentication;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Connections;
using Microsoft.AspNetCore.Http.Connections.Client;
using Microsoft.AspNetCore.Connections.Features;
using Microsoft.AspNetCore.Connections;
using MagoNet.Activation.Library;
using GiglioFattClassLibrary;
using ElaboratoreOrdiniClasses;
using DoorsAddoOnLibrary.Models;
using DoorsAddoOnLibrary.BillOfMaterialsComponents;
using DoorsAddoOnLibrary.LoginManager;
using DoorsAddoOnLibrary.TbServices;
using DoorsAddoOnLibrary;
using DevExpress.XtraVerticalGrid.Utils;
using DevExpress.XtraVerticalGrid.ViewInfo;
using DevExpress.XtraVerticalGrid.Events;
using DevExpress.XtraVerticalGrid.Editors;
using DevExpress.XtraVerticalGrid.Painters;
using DevExpress.XtraVerticalGrid.Localization;
using DevExpress.XtraVerticalGrid.Internal;
using DevExpress.XtraVerticalGrid.Design;
using DevExpress.XtraVerticalGrid.Data;
using DevExpress.XtraVerticalGrid.Rows;
using DevExpress.XtraVerticalGrid.Blending;
using DevExpress.XtraVerticalGrid;
using DevExpress.XtraVerticalGrid.Accessibility;
using DevExpress.XtraTreeList.Printing;
using DevExpress.XtraTreeList.ViewInfo;
using DevExpress.XtraTreeList.Menu;
using DevExpress.XtraTreeList.Helpers;
using DevExpress.XtraTreeList.Handler;
using DevExpress.XtraTreeList.Painter;
using DevExpress.XtraTreeList.Data;
using DevExpress.XtraTreeList.StyleFormatConditions;
using DevExpress.XtraTreeList.Scrolling;
using DevExpress.XtraTreeList.Frames;
using DevExpress.XtraTreeList.Design;
using DevExpress.XtraTreeList.Localization;
using DevExpress.XtraTreeList.Internal;
using DevExpress.XtraTreeList.Columns;
using DevExpress.XtraTreeList.FilterEditor;
using DevExpress.XtraTreeList.Nodes.Operations;
using DevExpress.XtraTreeList.Native;
using DevExpress.XtraTreeList.Nodes;
using DevExpress.XtraTreeList.Dragging;
using DevExpress.XtraTreeList.Accessibility;
using DevExpress.XtraTreeList.Blending;
using DevExpress.XtraTreeList;
using DevExpress.XtraEditors.Controls.Rtf;
using DevExpress.XtraFilterEditor.IntelliSense;
using DevExpress.XtraFilterEditor;
using DevExpress.XtraRichEdit.Painters;
using DevExpress.XtraRichEdit.Forms.Design;
using DevExpress.XtraRichEdit.API.RichTextBox;
using DevExpress.XtraRichEdit.API.Word;
using DevExpress.API.Mso;
using DevExpress.XtraPrinting.Preview.Native.Galleries;
using DevExpress.XtraPrinting.Preview.Native;
using DevExpress.XtraPrinting.Links;
using DevExpress.XtraPrinting.Control;
using DevExpress.XtraPrinting.Control.Native;
using DevExpress.XtraPrinting.CodedUISupport;
using DevExpress.XtraPrinting.Native.WinControls;
using DevExpress.XtraLayout.Tab;
using DevExpress.XtraLayout.Scrolling;
using DevExpress.XtraLayout.Registrator;
using DevExpress.XtraLayout.Localization;
using DevExpress.XtraLayout.Converter;
using DevExpress.XtraLayout.Printing;
using DevExpress.XtraLayout.Dragging;
using DevExpress.XtraLayout.Diagnostics;
using DevExpress.XtraDataLayout;
using DevExpress.XtraLayout.Helpers;
using DevExpress.XtraDashboardLayout;
using DevExpress.XtraLayout.Customization.Controls;
using DevExpress.XtraLayout.Utils;
using DevExpress.XtraLayout.Accessibility;
using DevExpress.XtraLayout.ViewInfo;
using DevExpress.XtraLayout.Painting;
using DevExpress.XtraLayout.HitInfo;
using DevExpress.XtraLayout.Customization;
using DevExpress.XtraLayout.Resizing;
using DevExpress.XtraLayout;
using DevExpress.XtraLayout.Handlers;
using DevExpress.XtraLayout.Adapters;
using DevExpress.XtraGrid.Repository;
using DevExpress.XtraGrid.Tab;
using DevExpress.XtraGrid.Filter.Parser;
using DevExpress.XtraGrid.Menu;
using DevExpress.XtraGrid.Filter;
using DevExpress.XtraGrid.Printing;
using DevExpress.XtraGrid.Editors;
using DevExpress.XtraGrid.Frames;
using DevExpress.XtraGrid.Registrator;
using DevExpress.XtraGrid.Views.Layout.Printing;
using DevExpress.XtraGrid.Views.Layout.Drawing;
using DevExpress.XtraGrid.Views.Layout.Modes;
using DevExpress.XtraGrid.Views.Layout.Customization;
using DevExpress.XtraGrid.Views.Layout.Events;
using DevExpress.XtraGrid.Views.Layout.ViewInfo;
using DevExpress.XtraGrid.Views.Layout.Frames;
using DevExpress.XtraGrid.Views.Layout.Handler;
using DevExpress.XtraGrid.Views.Layout.Designer;
using DevExpress.XtraGrid.Views.Layout;
using DevExpress.XtraGrid.GroupSummaryEditor;
using DevExpress.XtraGrid.Localization;
using DevExpress.XtraGrid.Drawing;
using DevExpress.XtraGrid.Internal;
using DevExpress.XtraGrid.FilterEditor;
using DevExpress.XtraGrid.Export;
using DevExpress.XtraGrid.Views.Card.ViewInfo;
using DevExpress.XtraGrid.Views.Card.Drawing;
using DevExpress.XtraGrid.Views.Card.Handler;
using DevExpress.XtraGrid.Views.Card;
using DevExpress.XtraGrid.Design;
using DevExpress.XtraGrid.Blending;
using DevExpress.XtraGrid.Helpers;
using DevExpress.XtraGrid.Controls;
using DevExpress.XtraGrid.Views.Printing;
using DevExpress.XtraGrid.Scrolling;
using DevExpress.XtraGrid.Accessibility;
using DevExpress.XtraGrid.Views.BandedGrid.Customization;
using DevExpress.XtraGrid.Views.Grid.Customization;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Skins;
using DevExpress.XtraGrid.Views.BandedGrid.ViewInfo;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using DevExpress.XtraGrid.Views.Base.ViewInfo;
using DevExpress.XtraGrid.Views.BandedGrid.Drawing;
using DevExpress.XtraGrid.Views.Grid.Drawing;
using DevExpress.XtraGrid.Views.BandedGrid;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.Base.Handler;
using DevExpress.XtraGrid.Views.Grid.Handler;
using DevExpress.XtraGrid.Views.BandedGrid.Handler;
using DevExpress.XtraGrid.Dragging;
using DevExpress.XtraEditors.FeatureBrowser;
using DevExpress.XtraTab.Buttons;
using DevExpress.XtraTab.Registrator;
using DevExpress.XtraTab.Drawing;
using DevExpress.XtraTab.ViewInfo;
using DevExpress.Accessibility.Tab;
using DevExpress.XtraWaitForm;
using DevExpress.XtraSplashForm;
using DevExpress.XtraSplashScreen;
using DevExpress.XtraEditors.Registrator;
using DevExpress.XtraEditors.Internal;
using DevExpress.XtraPivotGrid;
using DevExpress.XtraTab;
using DevExpress.XtraEditors.ColorPickEditControl;
using DevExpress.XtraEditors.Calendar;
using DevExpress.XtraEditors.NavigatorButtons;
using DevExpress.XtraEditors.Mask;
using DevExpress.XtraEditors.Popup;
using DevExpress.XtraEditors.Helpers;
using DevExpress.XtraEditors.Design;
using DevExpress.XtraEditors.Frames;
using DevExpress.XtraEditors.Customization;
using DevExpress.XtraEditors.ListControls;
using DevExpress.XtraEditors.Container;
using DevExpress.XtraEditors.CodedUISupport;
using DevExpress.XtraEditors.ButtonPanel;
using DevExpress.XtraEditors.Senders;
using DevExpress.XtraEditors.Persistent;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraBars.Ribbon.Customization;
using DevExpress.XtraBars.Docking.Controller;
using DevExpress.XtraBars.Docking2010.Dragging.WindowsUI;
using DevExpress.XtraBars.Docking2010.Views.NoDocuments;
using DevExpress.XtraBars.Docking2010.Views.NativeMdi;
using DevExpress.XtraBars.Docking2010.Views.WindowsUI;
using DevExpress.XtraBars.Commands.Internal;
using DevExpress.XtraBars.Commands.Ribbon;
using DevExpress.XtraBars.Commands;
using DevExpress.XtraBars.Commands.Design;
using DevExpress.XtraEditors.ColorPick.Popup.Galleries;
using DevExpress.XtraBars.ColorPick.Popup;
using DevExpress.XtraEditors.ColorPick.Picker;
using DevExpress.XtraBars.CodedUISupport;
using DevExpress.XtraBars.Editors;
using DevExpress.XtraTabbedMdi;
using DevExpress.XtraBars.Ribbon.Helpers;
using DevExpress.XtraBars.Ribbon.Internal;
using DevExpress.XtraBars.Ribbon.Gallery;
using DevExpress.XtraBars.Styles;
using DevExpress.XtraBars.Ribbon.Drawing;
using DevExpress.XtraBars.Ribbon.ViewInfo;
using DevExpress.XtraBars.Ribbon.Handler;
using DevExpress.XtraBars.Ribbon.Accessible;
using DevExpress.XtraBars.Localization;
using DevExpress.XtraBars.Design;
using DevExpress.XtraBars.Docking2010.Customization;
using DevExpress.XtraBars.InternalItems;
using DevExpress.XtraBars.Docking.Paint;
using DevExpress.XtraBars.Docking.Helpers;
using DevExpress.XtraBars.Docking;
using DevExpress.XtraBars.Docking2010.Dragging;
using DevExpress.XtraBars.Docking2010;
using DevExpress.XtraBars.Docking2010.DragEngine;
using DevExpress.XtraBars.Docking2010.Views.Tabbed;
using DevExpress.XtraBars.Docking2010.Views;
using DevExpress.XtraBars.Docking2010.Base;
using DevExpress.XtraBars.Ribbon;
using DevExpress.XtraBars.Customization.Helpers;
using DevExpress.XtraBars.Helpers.Docking;
using DevExpress.XtraBars.Forms;
using DevExpress.XtraBars.Registration;
using DevExpress.XtraBars.Helpers;
using DevExpress.XtraBars.ViewInfo;
using DevExpress.XtraBars.Objects;
using DevExpress.XtraBars.Native;
using DevExpress.XtraBars.MessageFilter;
using DevExpress.XtraBars.Painters;
using DevExpress.XtraBars.Utils;
using DevExpress.XtraBars;
using DevExpress.XtraBars.Controls;
using DevExpress.XtraBars.Alerter;
using DevExpress.XtraBars.Customization;
using DevExpress.XtraBars.Accessible;
using DevExpress.Utils.UI.Localization;
using DevExpress.Utils.UI;
using DevExpress.Utils.Frames;
using DevExpress.Utils.WXPaint;
using DevExpress.Utils.Mdi;
using DevExpress.Utils.Registrator;
using DevExpress.Utils.Native;
using DevExpress.Skins.Info;
using DevExpress.Skins.XtraForm;
using DevExpress.UserSkins;
using DevExpress.XtraReports.Serialization;
using DevExpress.XtraEditors.ViewInfo;
using DevExpress.Utils.NonclientArea;
using DevExpress.Utils.Drawing.Helpers;
using DevExpress.Utils.Helpers;
using DevExpress.Utils.Paint;
using DevExpress.LookAndFeel.Design;
using DevExpress.LookAndFeel.Helpers;
using DevExpress.Utils.Win.Hook;
using DevExpress.Utils.ViewInfo;
using DevExpress.Utils.ToolTip.ViewInfo;
using DevExpress.Utils.Extensions;
using DevExpress.XtraEditors.ScrollHelpers;
using DevExpress.Utils.Win;
using DevExpress.Utils.DragDrop;
using DevExpress.Skins;
using DevExpress.Utils.Gesture;
using DevExpress.Utils.Compress;
using DevExpress.Utils.CodedUISupport;
using DevExpress.Utils.Drawing;
using DevExpress.Utils.Drawing.Animation;
using DevExpress.Accessibility;
using DevExpress.LookAndFeel;
using DevExpress.XtraEditors.Drawing;
using DevExpress.XtraRichEdit.Internal.SimpleLayout;
using DevExpress.XtraRichEdit.Internal.ReadingLayout;
using DevExpress.XtraRichEdit.Internal.DraftLayout;
using DevExpress.XtraRichEdit.Internal.PrintLayout;
using DevExpress.XtraRichEdit.Design;
using DevExpress.XtraRichEdit.SyntaxEdit.Commands.Internal;
using DevExpress.XtraRichEdit.SyntaxEdit.Commands;
using DevExpress.XtraRichEdit.SyntaxEdit;
using DevExpress.XtraRichEdit.SyntaxEdit.Services.Implementation;
using DevExpress.XtraRichEdit.SpellChecker;
using DevExpress.XtraRichEdit.Services.Implementation;
using DevExpress.XtraRichEdit.Ruler;
using DevExpress.XtraPrinting.Native.RichText;
using DevExpress.XtraPrinting.Exports;
using DevExpress.XtraRichEdit.Printing;
using DevExpress.XtraRichEdit.Utils.NumberConverters;
using DevExpress.XtraRichEdit.Mouse;
using DevExpress.XtraRichEdit.Localization.Internal;
using DevExpress.XtraRichEdit.Localization;
using DevExpress.XtraRichEdit.Keyboard;
using DevExpress.XtraRichEdit.Design.Internal;
using DevExpress.XtraRichEdit.Menu;
using DevExpress.XtraRichEdit.Forms;
using DevExpress.XtraRichEdit.Fields.Expression;
using DevExpress.XtraRichEdit.Fields;
using DevExpress.XtraRichEdit.Model.History;
using DevExpress.XtraRichEdit.Layout.TableLayout;
using DevExpress.XtraRichEdit.Layout.Engine;
using DevExpress.XtraRichEdit.Layout.Export;
using DevExpress.XtraRichEdit.Import.Xaml;
using DevExpress.XtraRichEdit.Export.Xaml;
using DevExpress.XtraRichEdit.Import.WordML;
using DevExpress.XtraRichEdit.Export.WordML;
using DevExpress.XtraRichEdit.Import.Rtf.Tables;
using DevExpress.XtraRichEdit.Import.Rtf;
using DevExpress.XtraRichEdit.Export.PlainText;
using DevExpress.XtraRichEdit.Import.OpenXml;
using DevExpress.XtraRichEdit.Export.OpenXml;
using DevExpress.XtraRichEdit.Import.OpenDocument;
using DevExpress.XtraRichEdit.Export.OpenDocument;
using DevExpress.XtraRichEdit.Import.Mht;
using DevExpress.XtraRichEdit.Export.Mht;
using DevExpress.XtraRichEdit.Import.Html;
using DevExpress.XtraRichEdit.Import.EPub;
using DevExpress.XtraRichEdit.Export.Html;
using DevExpress.XtraRichEdit.Export.EPub;
using DevExpress.XtraRichEdit.Services;
using DevExpress.XtraRichEdit.Import;
using DevExpress.XtraRichEdit.Import.Doc;
using DevExpress.XtraRichEdit.Tables.Native;
using DevExpress.XtraRichEdit.Export.Doc;
using DevExpress.XtraRichEdit.Native;
using DevExpress.XtraRichEdit.Export;
using DevExpress.XtraRichEdit.Utils;
using DevExpress.XtraRichEdit.Commands.Helper;
using DevExpress.XtraRichEdit.Commands.Internal;
using DevExpress.XtraRichEdit.Commands;
using DevExpress.XtraRichEdit.Drawing;
using DevExpress.XtraRichEdit.Layout;
using DevExpress.XtraRichEdit.Internal;
using DevExpress.XtraRichEdit.API.Native.Implementation;
using DevExpress.XtraRichEdit.API.Native;
using DevExpress.XtraRichEdit.API.Internal;
using DevExpress.XtraRichEdit.Model;
using DevExpress.Printing.ServiceModel.DataContracts;
using DevExpress.Xpf.Printing.ServiceModel.DataContracts;
using DevExpress.XtraReports.ServiceModel.DataContracts;
using DevExpress.XtraPrinting.Drawing;
using DevExpress.XtraPrinting.Preview;
using DevExpress.Printing;
using DevExpress.XtraReports;
using DevExpress.XtraPrinting.InternalAccess;
using DevExpress.XtraPrinting.Export.Pdf.Compression;
using System.Collections;
using DevExpress.XtraPrinting.Native.LayoutAdjustment;
using DevExpress.XtraPrinting.Native.TextRotation;
using DevExpress.XtraPrinting.Native.Navigation;
using DevExpress.XtraPrinting.Native.Lines;
using DevExpress.XtraPrinting.HtmlExport;
using DevExpress.XtraPrinting.HtmlExport.Native;
using DevExpress.XtraPrinting.Export.XLS;
using DevExpress.XtraPrinting.Export.Text;
using DevExpress.XtraPrinting.Export.Rtf;
using DevExpress.XtraPrinting.Export.Imaging;
using DevExpress.XtraPrinting.Native.ExportOtions;
using DevExpress.XtraPrinting.Native.ExportOptionsControllers;
using DevExpress.XtraPrinting.Shape;
using DevExpress.XtraPrinting.Shape.Native;
using DevExpress.XtraPrinting.NativeBricks;
using DevExpress.XtraPrinting.Export.Pdf;
using DevExpress.XtraPrinting.Export;
using DevExpress.Printing.Core.Native;
using DevExpress.Printing.Core;
using DevExpress.XtraPrintingLinks;
using DevExpress.Printing.Core.HtmlExport;
using DevExpress.XtraPrinting.Export.Web;
using DevExpress.XtraPrinting.HtmlExport.Controls;
using DevExpress.XtraPrinting.BarCode.Native;
using DevExpress.XtraPrinting.BarCode;
using DevExpress.XtraPrinting.BrickExporters;
using DevExpress.Office.Services;
using DevExpress.Office.Services.Implementation;
using DevExpress.Office.Layout.Export;
using DevExpress.Office.Printing;
using DevExpress.Office.PInvoke;
using DevExpress.Office.Localization.Internal;
using DevExpress.Office.Localization;
using DevExpress.Office.Drawing;
using DevExpress.XtraRichEdit;
using DevExpress.Office.History;
using DevExpress.Office.Model;
using DevExpress.Office.Layout;
using DevExpress.Utils.StructuredStorage.Writer;
using DevExpress.Utils.StructuredStorage.Internal.Writer;
using DevExpress.Utils.StructuredStorage.Internal.Reader;
using DevExpress.Utils.StructuredStorage.Reader;
using DevExpress.Utils.StructuredStorage.Internal;
using DevExpress.Office.Utils;
using DevExpress.Office.Import;
using DevExpress.Office.Export;
using DevExpress.Office;
using DevExpress.Office.Internal;
using DevExpress.Office.API.Internal;
using DevExpress.Data.XtraReports.Wizard.Views;
using DevExpress.Data.XtraReports.Wizard.Presenters;
using DevExpress.Utils.Implementation;
using DevExpress.Data.Summary;
using DevExpress.Data.Async.Helpers;
using DevExpress.Schedule.Serializing;
using DevExpress.Schedule;
using DevExpress.Utils.Text.Internal;
using DevExpress.Data.Async;
using DevExpress.Data.Printing.Native;
using DevExpress.Utils.Zip;
using DevExpress.XtraPrinting.Localization;
using DevExpress.XtraPrinting.DataNodes;
using DevExpress.Data.ChartDataSources;
using DevExpress.Charts.Native;
using DevExpress.Xpo.Logger.Transport;
using DevExpress.Xpo.Logger;
using DevExpress.Utils.Text;
using DevExpress.XtraEditors.Filtering;
using DevExpress.XtraEditors;
using DevExpress.Data.ExpressionEditor;
using DevExpress.XtraExport;
using DevExpress.Data.Linq.Helpers;
using DevExpress.Data.Linq;
using DevExpress.Utils.Internal;
using DevExpress.Xpo.Providers;
using DevExpress.Data.Db;
using DevExpress.Data.Design;
using DevExpress.Xpo.XtraData;
using DevExpress.Data.Utils.ServiceModel.Native;
using DevExpress.CodeParser;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.DXErrorProvider;
using DevExpress.XtraPrinting;
using DevExpress.Internal;
using DevExpress.XtraPrinting.Design;
using DevExpress.Utils.Serializing.Helpers;
using DevExpress.Utils.Editors;
using DevExpress.Utils.Localization.Internal;
using DevExpress.Utils.Localization;
using DevExpress.Data.Utils;
using DevExpress.Utils.Serializing;
using DevExpress.WebUtils;
using DevExpress.Utils.Controls;
using DevExpress.Data.IO;
using DevExpress.XtraSpellChecker.Native;
using DevExpress.XtraSpellChecker.Parser;
using DevExpress.XtraSpellChecker;
using DevExpress.Services.Implementation;
using DevExpress.Services;
using DevExpress.XtraRichEdit.Export.Rtf;
using DevExpress.Data.Mask;
using DevExpress.Utils.KeyboardHandler;
using DevExpress.Utils.Design;
using DevExpress.Data.XtraReports.Wizard.Native;
using DevExpress.Data.XtraReports.Wizard;
using DevExpress.Data.XtraReports.ServiceModel.DataContracts;
using DevExpress.Data.XtraReports.ServiceModel;
using DevExpress.XtraReports.Parameters;
using DevExpress.Data.XtraReports.Native;
using DevExpress.Data.XtraReports.Labels;
using DevExpress.Data.XtraReports.DataProviders;
using DevExpress.XtraReports.Design.Commands;
using DevExpress.XtraReports.UserDesigner;
using DevExpress.XtraReports.Native.Parameters;
using DevExpress.XtraReports.UI;
using DevExpress.Data.WizardFramework;
using DevExpress.Utils.About;
using DevExpress.Data.Utils.ServiceModel;
using DevExpress.Utils.IoC;
using DevExpress.Xpf.Printing;
using DevExpress.XtraPrinting.Native;
using DevExpress.Utils.OAuth.Provider;
using DevExpress.Utils.OAuth;
using DevExpress.Utils.Gac;
using DevExpress.XtraGrid;
using DevExpress.Data.Filtering.Exceptions;
using DevExpress.Xpo;
using DevExpress.Utils.Extensions.Helpers;
using DevExpress.Data.Details;
using DevExpress.Xpo.Exceptions;
using DevExpress.Xpo.DB.Exceptions;
using DevExpress.Xpo.Helpers;
using DevExpress.Xpo.DB;
using DevExpress.Xpo.DB.Helpers;
using DevExpress.Data.Storage;
using DevExpress.Data.Access;
using DevExpress.Utils.Menu;
using DevExpress.Utils.Commands;
using DevExpress.Data.Filtering;
using DevExpress.Data.Helpers;
using DevExpress.Data.Selection;
using DevExpress.XtraReports.Native;
using DevExpress.XtraReports.Native.Data;
using DevExpress.Data.Browsing.Design;
using DevExpress.XtraReports.Design;
using DevExpress.Data;
using DevExpress.Services.Internal;
using DevExpress.Data.Browsing;
using DevExpress.Data.Filtering.Helpers;
using DevExpress.Data.Native;
using DevExpress.Utils;
using Cryptdll.classi;
using Cryptdll;
using MRG.Controls.UI;
using CLFtp;
using BusinessObjects.ERP.CustomersSuppliers.Documents.Suppliers;
using BusinessObjects.ERP.CustomersSuppliers.Documents.Customers;
using Microarea.Library.WCFGeneratedFunctions;
using System.Collections.Generic;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.OleDb;
using Microarea.EasyBuilder;
using Microarea.EasyBuilder.MVC;
using Microarea.TaskBuilderNet.UI.WinControls;
using Microarea.TaskBuilderNet.Interfaces.View;
using Microarea.TaskBuilderNet.Interfaces;
using Microarea.TaskBuilderNet.Core.CoreTypes;
using Microarea.TaskBuilderNet.Core.EasyBuilder;
using Microarea.TaskBuilderNet.Core.Generic;
using Microarea.Framework.TBApplicationWrapper;
using Microarea.TaskBuilderNet.Interfaces.Model;
using System.ComponentModel;
using System.Windows.Forms;
using System.Xml;
using System.Drawing;
using System.Data;
using System;
namespace Customization.Doors.Doors.DynamicDocuments.ImportCustSupp.ImportCustSupp
{
	public class BEDBTElencoCF : Microarea.Framework.TBApplicationWrapper.MBodyEdit
	{
		public BEDBTElencoCF(Microarea.TaskBuilderNet.Interfaces.View.IWindowWrapperContainer parentWindow, string controlName, string controlClass, System.Drawing.Point location, bool hasCodeBehind) : base(parentWindow, controlName, controlClass, location, hasCodeBehind)
		{
		}

		[Microarea.TaskBuilderNet.Core.EasyBuilder.PreserveFieldAttribute]
		public new MDImportCustSupp Document
		{
			get
			{
				return (MDImportCustSupp)DocumentController.controller.Document;
			}
		}

		public MBodyEditColumn col_Sel;

		public MBodyEditColumn col_NoteElab;

		public MBodyEditColumn col_Codice;

		public MBodyEditColumn col_RagSoc;

		public MBodyEditColumn col_Indirizzo;

		public MBodyEditColumn col_CAP;

		public MBodyEditColumn col_Citta;

		public MBodyEditColumn col_Provincia;

		public MBodyEditColumn col_Telefono;

		public MBodyEditColumn col_EMail;

		public MBodyEditColumn col_PartitaIva;

		public MBodyEditColumn col_DestMerce;

		public override void CreateComponents()
		{
			col_Sel = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Sel", "CheckBox", new System.Drawing.Point(0, 0), false);
			col_Sel.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_Sel, Document.DBTElencoCF);
			col_Sel.AddChangedProperty("DataBinding");
			col_Sel.ColPos = 0;
			col_Sel.AddChangedProperty("ColPos");
			col_Sel.SizeInChars = new System.Drawing.Size(1, 1);
			col_Sel.AddChangedProperty("SizeInChars");
			col_Sel.TitleTextColor = System.Drawing.Color.Black;
			col_Sel.AddChangedProperty("TitleTextColor");
			col_Sel.TitleBackColor = System.Drawing.Color.Transparent;
			col_Sel.AddChangedProperty("TitleBackColor");
			col_Sel.Visible = true;
			col_Sel.AddChangedProperty("Visible");
			col_Sel.AddChangedProperty("ColumnTitle");
			this.Add(col_Sel, false);
			col_NoteElab = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "NoteElab", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_NoteElab.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_NoteElab, Document.DBTElencoCF);
			col_NoteElab.AddChangedProperty("DataBinding");
			col_NoteElab.ColPos = 1;
			col_NoteElab.AddChangedProperty("ColPos");
			col_NoteElab.Width = 400;
			col_NoteElab.AddChangedProperty("Width");
			col_NoteElab.SizeInChars = new System.Drawing.Size(512, 1);
			col_NoteElab.AddChangedProperty("SizeInChars");
			col_NoteElab.TitleTextColor = System.Drawing.Color.Black;
			col_NoteElab.AddChangedProperty("TitleTextColor");
			col_NoteElab.TitleBackColor = System.Drawing.Color.Transparent;
			col_NoteElab.AddChangedProperty("TitleBackColor");
			col_NoteElab.Visible = true;
			col_NoteElab.AddChangedProperty("Visible");
			col_NoteElab.AddChangedProperty("ColumnTitle");
			this.Add(col_NoteElab, true);
			col_Codice = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Codice", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_Codice.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_Codice, Document.DBTElencoCF);
			col_Codice.AddChangedProperty("DataBinding");
			col_Codice.ColPos = 2;
			col_Codice.AddChangedProperty("ColPos");
			col_Codice.SizeInChars = new System.Drawing.Size(50, 1);
			col_Codice.AddChangedProperty("SizeInChars");
			col_Codice.TitleTextColor = System.Drawing.Color.Black;
			col_Codice.AddChangedProperty("TitleTextColor");
			col_Codice.TitleBackColor = System.Drawing.Color.Transparent;
			col_Codice.AddChangedProperty("TitleBackColor");
			col_Codice.Visible = true;
			col_Codice.AddChangedProperty("Visible");
			col_Codice.AddChangedProperty("ColumnTitle");
			this.Add(col_Codice, false);
			col_RagSoc = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "RagSoc", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_RagSoc.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_RagSoc, Document.DBTElencoCF);
			col_RagSoc.AddChangedProperty("DataBinding");
			col_RagSoc.ColPos = 3;
			col_RagSoc.AddChangedProperty("ColPos");
			col_RagSoc.SizeInChars = new System.Drawing.Size(50, 1);
			col_RagSoc.AddChangedProperty("SizeInChars");
			col_RagSoc.TitleTextColor = System.Drawing.Color.Black;
			col_RagSoc.AddChangedProperty("TitleTextColor");
			col_RagSoc.TitleBackColor = System.Drawing.Color.Transparent;
			col_RagSoc.AddChangedProperty("TitleBackColor");
			col_RagSoc.Visible = true;
			col_RagSoc.AddChangedProperty("Visible");
			col_RagSoc.AddChangedProperty("ColumnTitle");
			this.Add(col_RagSoc, false);
			col_Indirizzo = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Indirizzo", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_Indirizzo.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_Indirizzo, Document.DBTElencoCF);
			col_Indirizzo.AddChangedProperty("DataBinding");
			col_Indirizzo.ColPos = 4;
			col_Indirizzo.AddChangedProperty("ColPos");
			col_Indirizzo.SizeInChars = new System.Drawing.Size(150, 1);
			col_Indirizzo.AddChangedProperty("SizeInChars");
			col_Indirizzo.TitleTextColor = System.Drawing.Color.Black;
			col_Indirizzo.AddChangedProperty("TitleTextColor");
			col_Indirizzo.TitleBackColor = System.Drawing.Color.Transparent;
			col_Indirizzo.AddChangedProperty("TitleBackColor");
			col_Indirizzo.Visible = true;
			col_Indirizzo.AddChangedProperty("Visible");
			col_Indirizzo.AddChangedProperty("ColumnTitle");
			this.Add(col_Indirizzo, false);
			col_CAP = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "CAP", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_CAP.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_CAP, Document.DBTElencoCF);
			col_CAP.AddChangedProperty("DataBinding");
			col_CAP.ColPos = 5;
			col_CAP.AddChangedProperty("ColPos");
			col_CAP.SizeInChars = new System.Drawing.Size(50, 1);
			col_CAP.AddChangedProperty("SizeInChars");
			col_CAP.TitleTextColor = System.Drawing.Color.Black;
			col_CAP.AddChangedProperty("TitleTextColor");
			col_CAP.TitleBackColor = System.Drawing.Color.Transparent;
			col_CAP.AddChangedProperty("TitleBackColor");
			col_CAP.Visible = true;
			col_CAP.AddChangedProperty("Visible");
			col_CAP.AddChangedProperty("ColumnTitle");
			this.Add(col_CAP, false);
			col_Citta = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Citta", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_Citta.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_Citta, Document.DBTElencoCF);
			col_Citta.AddChangedProperty("DataBinding");
			col_Citta.ColPos = 6;
			col_Citta.AddChangedProperty("ColPos");
			col_Citta.SizeInChars = new System.Drawing.Size(150, 1);
			col_Citta.AddChangedProperty("SizeInChars");
			col_Citta.TitleTextColor = System.Drawing.Color.Black;
			col_Citta.AddChangedProperty("TitleTextColor");
			col_Citta.TitleBackColor = System.Drawing.Color.Transparent;
			col_Citta.AddChangedProperty("TitleBackColor");
			col_Citta.Visible = true;
			col_Citta.AddChangedProperty("Visible");
			col_Citta.AddChangedProperty("ColumnTitle");
			this.Add(col_Citta, false);
			col_Provincia = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Provincia", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_Provincia.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_Provincia, Document.DBTElencoCF);
			col_Provincia.AddChangedProperty("DataBinding");
			col_Provincia.ColPos = 7;
			col_Provincia.AddChangedProperty("ColPos");
			col_Provincia.SizeInChars = new System.Drawing.Size(50, 1);
			col_Provincia.AddChangedProperty("SizeInChars");
			col_Provincia.TitleTextColor = System.Drawing.Color.Black;
			col_Provincia.AddChangedProperty("TitleTextColor");
			col_Provincia.TitleBackColor = System.Drawing.Color.Transparent;
			col_Provincia.AddChangedProperty("TitleBackColor");
			col_Provincia.Visible = true;
			col_Provincia.AddChangedProperty("Visible");
			col_Provincia.AddChangedProperty("ColumnTitle");
			this.Add(col_Provincia, false);
			col_Telefono = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "Telefono", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_Telefono.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_Telefono, Document.DBTElencoCF);
			col_Telefono.AddChangedProperty("DataBinding");
			col_Telefono.ColPos = 8;
			col_Telefono.AddChangedProperty("ColPos");
			col_Telefono.SizeInChars = new System.Drawing.Size(50, 1);
			col_Telefono.AddChangedProperty("SizeInChars");
			col_Telefono.TitleTextColor = System.Drawing.Color.Black;
			col_Telefono.AddChangedProperty("TitleTextColor");
			col_Telefono.TitleBackColor = System.Drawing.Color.Transparent;
			col_Telefono.AddChangedProperty("TitleBackColor");
			col_Telefono.Visible = true;
			col_Telefono.AddChangedProperty("Visible");
			col_Telefono.AddChangedProperty("ColumnTitle");
			this.Add(col_Telefono, false);
			col_EMail = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "EMail", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_EMail.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_EMail, Document.DBTElencoCF);
			col_EMail.AddChangedProperty("DataBinding");
			col_EMail.ColPos = 9;
			col_EMail.AddChangedProperty("ColPos");
			col_EMail.SizeInChars = new System.Drawing.Size(200, 1);
			col_EMail.AddChangedProperty("SizeInChars");
			col_EMail.TitleTextColor = System.Drawing.Color.Black;
			col_EMail.AddChangedProperty("TitleTextColor");
			col_EMail.TitleBackColor = System.Drawing.Color.Transparent;
			col_EMail.AddChangedProperty("TitleBackColor");
			col_EMail.Visible = true;
			col_EMail.AddChangedProperty("Visible");
			col_EMail.AddChangedProperty("ColumnTitle");
			this.Add(col_EMail, false);
			col_PartitaIva = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "PartitaIva", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_PartitaIva.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_PartitaIva, Document.DBTElencoCF);
			col_PartitaIva.AddChangedProperty("DataBinding");
			col_PartitaIva.ColPos = 10;
			col_PartitaIva.AddChangedProperty("ColPos");
			col_PartitaIva.SizeInChars = new System.Drawing.Size(50, 1);
			col_PartitaIva.AddChangedProperty("SizeInChars");
			col_PartitaIva.TitleTextColor = System.Drawing.Color.Black;
			col_PartitaIva.AddChangedProperty("TitleTextColor");
			col_PartitaIva.TitleBackColor = System.Drawing.Color.Transparent;
			col_PartitaIva.AddChangedProperty("TitleBackColor");
			col_PartitaIva.Visible = true;
			col_PartitaIva.AddChangedProperty("Visible");
			col_PartitaIva.AddChangedProperty("ColumnTitle");
			this.Add(col_PartitaIva, false);
			col_DestMerce = new Microarea.Framework.TBApplicationWrapper.MBodyEditColumn(this, "DestMerce", "StringEdit", new System.Drawing.Point(0, 0), false);
			col_DestMerce.DataBinding = new FieldDataBinding(Document.DBTElencoCF.TEB_LocalData.fld_DestMerce, Document.DBTElencoCF);
			col_DestMerce.AddChangedProperty("DataBinding");
			col_DestMerce.ColPos = 11;
			col_DestMerce.AddChangedProperty("ColPos");
			col_DestMerce.SizeInChars = new System.Drawing.Size(250, 1);
			col_DestMerce.AddChangedProperty("SizeInChars");
			col_DestMerce.TitleTextColor = System.Drawing.Color.Black;
			col_DestMerce.AddChangedProperty("TitleTextColor");
			col_DestMerce.TitleBackColor = System.Drawing.Color.Transparent;
			col_DestMerce.AddChangedProperty("TitleBackColor");
			col_DestMerce.Visible = true;
			col_DestMerce.AddChangedProperty("Visible");
			col_DestMerce.AddChangedProperty("ColumnTitle");
			this.Add(col_DestMerce, false);
		}

		public override void ApplyResources()
		{
			Microarea.EasyBuilder.CustomizationComponentResourceManager resources = Strings.ResourceManager;
			resources.ApplyResources(col_Sel, "col_Sel");
			resources.ApplyResources(col_NoteElab, "col_NoteElab");
			resources.ApplyResources(col_Codice, "col_Codice");
			resources.ApplyResources(col_RagSoc, "col_RagSoc");
			resources.ApplyResources(col_Indirizzo, "col_Indirizzo");
			resources.ApplyResources(col_CAP, "col_CAP");
			resources.ApplyResources(col_Citta, "col_Citta");
			resources.ApplyResources(col_Provincia, "col_Provincia");
			resources.ApplyResources(col_Telefono, "col_Telefono");
			resources.ApplyResources(col_EMail, "col_EMail");
			resources.ApplyResources(col_PartitaIva, "col_PartitaIva");
			resources.ApplyResources(col_DestMerce, "col_DestMerce");
		}

		public override void ClearComponents()
		{
			base.ClearComponents();
			col_Sel = null;
			col_NoteElab = null;
			col_Codice = null;
			col_RagSoc = null;
			col_Indirizzo = null;
			col_CAP = null;
			col_Citta = null;
			col_Provincia = null;
			col_Telefono = null;
			col_EMail = null;
			col_PartitaIva = null;
			col_DestMerce = null;
		}
	}
}
