ALTER TABLE "MA_ITEMS"
ADD "DOORSLARGHEZZA" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSLARGHEZZA" = 0 WHERE "DOORSLARGHEZZA" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSALTEZZA" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSALTEZZA" = 0 WHERE "DOORSALTEZZA" IS NULL
GO


