ALTER TABLE "MA_ITEMS"
ADD "DOORSARIAL" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSARIAL" = 0 WHERE "DOORSARIAL" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSARIAH" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSARIAH" = 0 WHERE "DOORSARIAH" IS NULL
GO


