ALTER TABLE "TAG_DOORS_MAGGIORAZIONIDETAIL"
ADD "TIPOMAGGIORAZIONE" NUMBER (10) DEFAULT (996409344)
GO


UPDATE "TAG_DOORS_MAGGIORAZIONIDETAIL" SET "TIPOMAGGIORAZIONE" = 996409344 WHERE "TIPOMAGGIORAZIONE" IS NULL
GO


