using Wv2Edge;
using System.Threading.Channels;
using System.Text.Json.Serialization;
using System.Text.Json;
using System.Text.Encodings.Web;
using System.Text.Unicode;
using System.Numerics;
using System.Buffers.Binary;
using System.Buffers.Text;
using System.IO.Pipelines;
using System.Runtime.InteropServices;
using System.IO.MemoryMappedFiles;
using System.Threading;
using System.IO.Pipes;
using System.IO;
using System.Diagnostics.PerformanceData;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Dynamic;
using System.Security.Cryptography.X509Certificates;
using System.Security.Cryptography;
using System.Security;
using Microsoft.Win32.SafeHandles;
using System.Linq;
using System.Diagnostics.Eventing.Reader;
using System.Management.Instrumentation;
using System.Diagnostics.Eventing;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Buffers;
using RestSharp.Validation;
using RestSharp.Serializers;
using RestSharp.Contrib;
using RestSharp.Extensions;
using RestSharp.Deserializers;
using RestSharp.Authenticators.OAuth;
using RestSharp.Authenticators;
using RestSharp;
using OpenCartGateClasses;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Schema;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json;
using Microsoft.Web.WebView2.WinForms;
using Microsoft.Web.WebView2.Core.Raw;
using Microsoft.Web.WebView2.Core;
using Microsoft.Extensions.Primitives;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Configuration.Memory;
using Microsoft.Extensions.Configuration;
using System.Threading.Tasks.Sources;
using System.Threading.Tasks;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.SignalR.Protocol;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Features.Authentication;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Connections;
using Microsoft.AspNetCore.Http.Connections.Client;
using Microsoft.AspNetCore.Connections.Features;
using Microsoft.AspNetCore.Connections;
using ElaboratoreOrdiniClasses;
using DoorsAddoOnLibrary.Models;
using DoorsAddoOnLibrary.BillOfMaterialsComponents;
using DoorsAddoOnLibrary.LoginManager;
using DoorsAddoOnLibrary.TbServices;
using DoorsAddoOnLibrary;
using DevExpress.XtraVerticalGrid.Utils;
using DevExpress.XtraVerticalGrid.ViewInfo;
using DevExpress.XtraVerticalGrid.Events;
using DevExpress.XtraVerticalGrid.Editors;
using DevExpress.XtraVerticalGrid.Painters;
using DevExpress.XtraVerticalGrid.Localization;
using DevExpress.XtraVerticalGrid.Internal;
using DevExpress.XtraVerticalGrid.Design;
using DevExpress.XtraVerticalGrid.Data;
using DevExpress.XtraVerticalGrid.Rows;
using DevExpress.XtraVerticalGrid.Blending;
using DevExpress.XtraVerticalGrid;
using DevExpress.XtraVerticalGrid.Accessibility;
using DevExpress.XtraTreeList.Printing;
using DevExpress.XtraTreeList.ViewInfo;
using DevExpress.XtraTreeList.Menu;
using DevExpress.XtraTreeList.Helpers;
using DevExpress.XtraTreeList.Handler;
using DevExpress.XtraTreeList.Painter;
using DevExpress.XtraTreeList.Data;
using DevExpress.XtraTreeList.StyleFormatConditions;
using DevExpress.XtraTreeList.Scrolling;
using DevExpress.XtraTreeList.Frames;
using DevExpress.XtraTreeList.Design;
using DevExpress.XtraTreeList.Localization;
using DevExpress.XtraTreeList.Internal;
using DevExpress.XtraTreeList.Columns;
using DevExpress.XtraTreeList.FilterEditor;
using DevExpress.XtraTreeList.Nodes.Operations;
using DevExpress.XtraTreeList.Native;
using DevExpress.XtraTreeList.Nodes;
using DevExpress.XtraTreeList.Dragging;
using DevExpress.XtraTreeList.Accessibility;
using DevExpress.XtraTreeList.Blending;
using DevExpress.XtraTreeList;
using DevExpress.XtraEditors.Controls.Rtf;
using DevExpress.XtraFilterEditor.IntelliSense;
using DevExpress.XtraFilterEditor;
using DevExpress.XtraRichEdit.Painters;
using DevExpress.XtraRichEdit.Forms.Design;
using DevExpress.XtraRichEdit.API.RichTextBox;
using DevExpress.XtraRichEdit.API.Word;
using DevExpress.API.Mso;
using DevExpress.XtraPrinting.Preview.Native.Galleries;
using DevExpress.XtraPrinting.Preview.Native;
using DevExpress.XtraPrinting.Links;
using DevExpress.XtraPrinting.Control;
using DevExpress.XtraPrinting.Control.Native;
using DevExpress.XtraPrinting.CodedUISupport;
using DevExpress.XtraPrinting.Native.WinControls;
using DevExpress.XtraLayout.Tab;
using DevExpress.XtraLayout.Scrolling;
using DevExpress.XtraLayout.Registrator;
using DevExpress.XtraLayout.Localization;
using DevExpress.XtraLayout.Converter;
using DevExpress.XtraLayout.Printing;
using DevExpress.XtraLayout.Dragging;
using DevExpress.XtraLayout.Diagnostics;
using DevExpress.XtraDataLayout;
using DevExpress.XtraLayout.Helpers;
using DevExpress.XtraDashboardLayout;
using DevExpress.XtraLayout.Customization.Controls;
using DevExpress.XtraLayout.Utils;
using DevExpress.XtraLayout.Accessibility;
using DevExpress.XtraLayout.ViewInfo;
using DevExpress.XtraLayout.Painting;
using DevExpress.XtraLayout.HitInfo;
using DevExpress.XtraLayout.Customization;
using DevExpress.XtraLayout.Resizing;
using DevExpress.XtraLayout;
using DevExpress.XtraLayout.Handlers;
using DevExpress.XtraLayout.Adapters;
using DevExpress.XtraGrid.Repository;
using DevExpress.XtraGrid.Tab;
using DevExpress.XtraGrid.Filter.Parser;
using DevExpress.XtraGrid.Menu;
using DevExpress.XtraGrid.Filter;
using DevExpress.XtraGrid.Printing;
using DevExpress.XtraGrid.Editors;
using DevExpress.XtraGrid.Frames;
using DevExpress.XtraGrid.Registrator;
using DevExpress.XtraGrid.Views.Layout.Printing;
using DevExpress.XtraGrid.Views.Layout.Drawing;
using DevExpress.XtraGrid.Views.Layout.Modes;
using DevExpress.XtraGrid.Views.Layout.Customization;
using DevExpress.XtraGrid.Views.Layout.Events;
using DevExpress.XtraGrid.Views.Layout.ViewInfo;
using DevExpress.XtraGrid.Views.Layout.Frames;
using DevExpress.XtraGrid.Views.Layout.Handler;
using DevExpress.XtraGrid.Views.Layout.Designer;
using DevExpress.XtraGrid.Views.Layout;
using DevExpress.XtraGrid.GroupSummaryEditor;
using DevExpress.XtraGrid.Localization;
using DevExpress.XtraGrid.Drawing;
using DevExpress.XtraGrid.Internal;
using DevExpress.XtraGrid.FilterEditor;
using DevExpress.XtraGrid.Export;
using DevExpress.XtraGrid.Views.Card.ViewInfo;
using DevExpress.XtraGrid.Views.Card.Drawing;
using DevExpress.XtraGrid.Views.Card.Handler;
using DevExpress.XtraGrid.Views.Card;
using DevExpress.XtraGrid.Design;
using DevExpress.XtraGrid.Blending;
using DevExpress.XtraGrid.Helpers;
using DevExpress.XtraGrid.Controls;
using DevExpress.XtraGrid.Views.Printing;
using DevExpress.XtraGrid.Scrolling;
using DevExpress.XtraGrid.Accessibility;
using DevExpress.XtraGrid.Views.BandedGrid.Customization;
using DevExpress.XtraGrid.Views.Grid.Customization;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Skins;
using DevExpress.XtraGrid.Views.BandedGrid.ViewInfo;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using DevExpress.XtraGrid.Views.Base.ViewInfo;
using DevExpress.XtraGrid.Views.BandedGrid.Drawing;
using DevExpress.XtraGrid.Views.Grid.Drawing;
using DevExpress.XtraGrid.Views.BandedGrid;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.Base.Handler;
using DevExpress.XtraGrid.Views.Grid.Handler;
using DevExpress.XtraGrid.Views.BandedGrid.Handler;
using DevExpress.XtraGrid.Dragging;
using DevExpress.XtraEditors.FeatureBrowser;
using DevExpress.XtraTab.Buttons;
using DevExpress.XtraTab.Registrator;
using DevExpress.XtraTab.Drawing;
using DevExpress.XtraTab.ViewInfo;
using DevExpress.Accessibility.Tab;
using DevExpress.XtraWaitForm;
using DevExpress.XtraSplashForm;
using DevExpress.XtraSplashScreen;
using DevExpress.XtraEditors.Registrator;
using DevExpress.XtraEditors.Internal;
using DevExpress.XtraPivotGrid;
using DevExpress.XtraTab;
using DevExpress.XtraEditors.ColorPickEditControl;
using DevExpress.XtraEditors.Calendar;
using DevExpress.XtraEditors.NavigatorButtons;
using DevExpress.XtraEditors.Mask;
using DevExpress.XtraEditors.Popup;
using DevExpress.XtraEditors.Helpers;
using DevExpress.XtraEditors.Design;
using DevExpress.XtraEditors.Frames;
using DevExpress.XtraEditors.Customization;
using DevExpress.XtraEditors.ListControls;
using DevExpress.XtraEditors.Container;
using DevExpress.XtraEditors.CodedUISupport;
using DevExpress.XtraEditors.ButtonPanel;
using DevExpress.XtraEditors.Senders;
using DevExpress.XtraEditors.Persistent;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraBars.Ribbon.Customization;
using DevExpress.XtraBars.Docking.Controller;
using DevExpress.XtraBars.Docking2010.Dragging.WindowsUI;
using DevExpress.XtraBars.Docking2010.Views.NoDocuments;
using DevExpress.XtraBars.Docking2010.Views.NativeMdi;
using DevExpress.XtraBars.Docking2010.Views.WindowsUI;
using DevExpress.XtraBars.Commands.Internal;
using DevExpress.XtraBars.Commands.Ribbon;
using DevExpress.XtraBars.Commands;
using DevExpress.XtraBars.Commands.Design;
using DevExpress.XtraEditors.ColorPick.Popup.Galleries;
using DevExpress.XtraBars.ColorPick.Popup;
using DevExpress.XtraEditors.ColorPick.Picker;
using DevExpress.XtraBars.CodedUISupport;
using DevExpress.XtraBars.Editors;
using DevExpress.XtraTabbedMdi;
using DevExpress.XtraBars.Ribbon.Helpers;
using DevExpress.XtraBars.Ribbon.Internal;
using DevExpress.XtraBars.Ribbon.Gallery;
using DevExpress.XtraBars.Styles;
using DevExpress.XtraBars.Ribbon.Drawing;
using DevExpress.XtraBars.Ribbon.ViewInfo;
using DevExpress.XtraBars.Ribbon.Handler;
using DevExpress.XtraBars.Ribbon.Accessible;
using DevExpress.XtraBars.Localization;
using DevExpress.XtraBars.Design;
using DevExpress.XtraBars.Docking2010.Customization;
using DevExpress.XtraBars.InternalItems;
using DevExpress.XtraBars.Docking.Paint;
using DevExpress.XtraBars.Docking.Helpers;
using DevExpress.XtraBars.Docking;
using DevExpress.XtraBars.Docking2010.Dragging;
using DevExpress.XtraBars.Docking2010;
using DevExpress.XtraBars.Docking2010.DragEngine;
using DevExpress.XtraBars.Docking2010.Views.Tabbed;
using DevExpress.XtraBars.Docking2010.Views;
using DevExpress.XtraBars.Docking2010.Base;
using DevExpress.XtraBars.Ribbon;
using DevExpress.XtraBars.Customization.Helpers;
using DevExpress.XtraBars.Helpers.Docking;
using DevExpress.XtraBars.Forms;
using DevExpress.XtraBars.Registration;
using DevExpress.XtraBars.Helpers;
using DevExpress.XtraBars.ViewInfo;
using DevExpress.XtraBars.Objects;
using DevExpress.XtraBars.Native;
using DevExpress.XtraBars.MessageFilter;
using DevExpress.XtraBars.Painters;
using DevExpress.XtraBars.Utils;
using DevExpress.XtraBars;
using DevExpress.XtraBars.Controls;
using DevExpress.XtraBars.Alerter;
using DevExpress.XtraBars.Customization;
using DevExpress.XtraBars.Accessible;
using DevExpress.Utils.UI.Localization;
using DevExpress.Utils.UI;
using DevExpress.Utils.Frames;
using DevExpress.Utils.WXPaint;
using DevExpress.Utils.Mdi;
using DevExpress.Utils.Registrator;
using DevExpress.Utils.Native;
using DevExpress.Skins.Info;
using DevExpress.Skins.XtraForm;
using DevExpress.UserSkins;
using DevExpress.XtraReports.Serialization;
using DevExpress.XtraEditors.ViewInfo;
using DevExpress.Utils.NonclientArea;
using DevExpress.Utils.Drawing.Helpers;
using DevExpress.Utils.Helpers;
using DevExpress.Utils.Paint;
using DevExpress.LookAndFeel.Design;
using DevExpress.LookAndFeel.Helpers;
using DevExpress.Utils.Win.Hook;
using DevExpress.Utils.ViewInfo;
using DevExpress.Utils.ToolTip.ViewInfo;
using DevExpress.Utils.Extensions;
using DevExpress.XtraEditors.ScrollHelpers;
using DevExpress.Utils.Win;
using DevExpress.Utils.DragDrop;
using DevExpress.Skins;
using DevExpress.Utils.Gesture;
using DevExpress.Utils.Compress;
using DevExpress.Utils.CodedUISupport;
using DevExpress.Utils.Drawing;
using DevExpress.Utils.Drawing.Animation;
using DevExpress.Accessibility;
using DevExpress.LookAndFeel;
using DevExpress.XtraEditors.Drawing;
using DevExpress.XtraRichEdit.Internal.SimpleLayout;
using DevExpress.XtraRichEdit.Internal.ReadingLayout;
using DevExpress.XtraRichEdit.Internal.DraftLayout;
using DevExpress.XtraRichEdit.Internal.PrintLayout;
using DevExpress.XtraRichEdit.Design;
using DevExpress.XtraRichEdit.SyntaxEdit.Commands.Internal;
using DevExpress.XtraRichEdit.SyntaxEdit.Commands;
using DevExpress.XtraRichEdit.SyntaxEdit;
using DevExpress.XtraRichEdit.SyntaxEdit.Services.Implementation;
using DevExpress.XtraRichEdit.SpellChecker;
using DevExpress.XtraRichEdit.Services.Implementation;
using DevExpress.XtraRichEdit.Ruler;
using DevExpress.XtraPrinting.Native.RichText;
using DevExpress.XtraPrinting.Exports;
using DevExpress.XtraRichEdit.Printing;
using DevExpress.XtraRichEdit.Utils.NumberConverters;
using DevExpress.XtraRichEdit.Mouse;
using DevExpress.XtraRichEdit.Localization.Internal;
using DevExpress.XtraRichEdit.Localization;
using DevExpress.XtraRichEdit.Keyboard;
using DevExpress.XtraRichEdit.Design.Internal;
using DevExpress.XtraRichEdit.Menu;
using DevExpress.XtraRichEdit.Forms;
using DevExpress.XtraRichEdit.Fields.Expression;
using DevExpress.XtraRichEdit.Fields;
using DevExpress.XtraRichEdit.Model.History;
using DevExpress.XtraRichEdit.Layout.TableLayout;
using DevExpress.XtraRichEdit.Layout.Engine;
using DevExpress.XtraRichEdit.Layout.Export;
using DevExpress.XtraRichEdit.Import.Xaml;
using DevExpress.XtraRichEdit.Export.Xaml;
using DevExpress.XtraRichEdit.Import.WordML;
using DevExpress.XtraRichEdit.Export.WordML;
using DevExpress.XtraRichEdit.Import.Rtf.Tables;
using DevExpress.XtraRichEdit.Import.Rtf;
using DevExpress.XtraRichEdit.Export.PlainText;
using DevExpress.XtraRichEdit.Import.OpenXml;
using DevExpress.XtraRichEdit.Export.OpenXml;
using DevExpress.XtraRichEdit.Import.OpenDocument;
using DevExpress.XtraRichEdit.Export.OpenDocument;
using DevExpress.XtraRichEdit.Import.Mht;
using DevExpress.XtraRichEdit.Export.Mht;
using DevExpress.XtraRichEdit.Import.Html;
using DevExpress.XtraRichEdit.Import.EPub;
using DevExpress.XtraRichEdit.Export.Html;
using DevExpress.XtraRichEdit.Export.EPub;
using DevExpress.XtraRichEdit.Services;
using DevExpress.XtraRichEdit.Import;
using DevExpress.XtraRichEdit.Import.Doc;
using DevExpress.XtraRichEdit.Tables.Native;
using DevExpress.XtraRichEdit.Export.Doc;
using DevExpress.XtraRichEdit.Native;
using DevExpress.XtraRichEdit.Export;
using DevExpress.XtraRichEdit.Utils;
using DevExpress.XtraRichEdit.Commands.Helper;
using DevExpress.XtraRichEdit.Commands.Internal;
using DevExpress.XtraRichEdit.Commands;
using DevExpress.XtraRichEdit.Drawing;
using DevExpress.XtraRichEdit.Layout;
using DevExpress.XtraRichEdit.Internal;
using DevExpress.XtraRichEdit.API.Native.Implementation;
using DevExpress.XtraRichEdit.API.Native;
using DevExpress.XtraRichEdit.API.Internal;
using DevExpress.XtraRichEdit.Model;
using DevExpress.Printing.ServiceModel.DataContracts;
using DevExpress.Xpf.Printing.ServiceModel.DataContracts;
using DevExpress.XtraReports.ServiceModel.DataContracts;
using DevExpress.XtraPrinting.Drawing;
using DevExpress.XtraPrinting.Preview;
using DevExpress.Printing;
using DevExpress.XtraReports;
using DevExpress.XtraPrinting.InternalAccess;
using DevExpress.XtraPrinting.Export.Pdf.Compression;
using System.Collections;
using DevExpress.XtraPrinting.Native.LayoutAdjustment;
using DevExpress.XtraPrinting.Native.TextRotation;
using DevExpress.XtraPrinting.Native.Navigation;
using DevExpress.XtraPrinting.Native.Lines;
using DevExpress.XtraPrinting.HtmlExport;
using DevExpress.XtraPrinting.HtmlExport.Native;
using DevExpress.XtraPrinting.Export.XLS;
using DevExpress.XtraPrinting.Export.Text;
using DevExpress.XtraPrinting.Export.Rtf;
using DevExpress.XtraPrinting.Export.Imaging;
using DevExpress.XtraPrinting.Native.ExportOtions;
using DevExpress.XtraPrinting.Native.ExportOptionsControllers;
using DevExpress.XtraPrinting.Shape;
using DevExpress.XtraPrinting.Shape.Native;
using DevExpress.XtraPrinting.NativeBricks;
using DevExpress.XtraPrinting.Export.Pdf;
using DevExpress.XtraPrinting.Export;
using DevExpress.Printing.Core.Native;
using DevExpress.Printing.Core;
using DevExpress.XtraPrintingLinks;
using DevExpress.Printing.Core.HtmlExport;
using DevExpress.XtraPrinting.Export.Web;
using DevExpress.XtraPrinting.HtmlExport.Controls;
using DevExpress.XtraPrinting.BarCode.Native;
using DevExpress.XtraPrinting.BarCode;
using DevExpress.XtraPrinting.BrickExporters;
using DevExpress.Office.Services;
using DevExpress.Office.Services.Implementation;
using DevExpress.Office.Layout.Export;
using DevExpress.Office.Printing;
using DevExpress.Office.PInvoke;
using DevExpress.Office.Localization.Internal;
using DevExpress.Office.Localization;
using DevExpress.Office.Drawing;
using DevExpress.XtraRichEdit;
using DevExpress.Office.History;
using DevExpress.Office.Model;
using DevExpress.Office.Layout;
using DevExpress.Utils.StructuredStorage.Writer;
using DevExpress.Utils.StructuredStorage.Internal.Writer;
using DevExpress.Utils.StructuredStorage.Internal.Reader;
using DevExpress.Utils.StructuredStorage.Reader;
using DevExpress.Utils.StructuredStorage.Internal;
using DevExpress.Office.Utils;
using DevExpress.Office.Import;
using DevExpress.Office.Export;
using DevExpress.Office;
using DevExpress.Office.Internal;
using DevExpress.Office.API.Internal;
using DevExpress.Data.XtraReports.Wizard.Views;
using DevExpress.Data.XtraReports.Wizard.Presenters;
using DevExpress.Utils.Implementation;
using DevExpress.Data.Summary;
using DevExpress.Data.Async.Helpers;
using DevExpress.Schedule.Serializing;
using DevExpress.Schedule;
using DevExpress.Utils.Text.Internal;
using DevExpress.Data.Async;
using DevExpress.Data.Printing.Native;
using DevExpress.Utils.Zip;
using DevExpress.XtraPrinting.Localization;
using DevExpress.XtraPrinting.DataNodes;
using DevExpress.Data.ChartDataSources;
using DevExpress.Charts.Native;
using DevExpress.Xpo.Logger.Transport;
using DevExpress.Xpo.Logger;
using DevExpress.Utils.Text;
using DevExpress.XtraEditors.Filtering;
using DevExpress.XtraEditors;
using DevExpress.Data.ExpressionEditor;
using DevExpress.XtraExport;
using DevExpress.Data.Linq.Helpers;
using DevExpress.Data.Linq;
using DevExpress.Utils.Internal;
using DevExpress.Xpo.Providers;
using DevExpress.Data.Db;
using DevExpress.Data.Design;
using DevExpress.Xpo.XtraData;
using DevExpress.Data.Utils.ServiceModel.Native;
using DevExpress.CodeParser;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.DXErrorProvider;
using DevExpress.XtraPrinting;
using DevExpress.Internal;
using DevExpress.XtraPrinting.Design;
using DevExpress.Utils.Serializing.Helpers;
using DevExpress.Utils.Editors;
using DevExpress.Utils.Localization.Internal;
using DevExpress.Utils.Localization;
using DevExpress.Data.Utils;
using DevExpress.Utils.Serializing;
using DevExpress.WebUtils;
using DevExpress.Utils.Controls;
using DevExpress.Data.IO;
using DevExpress.XtraSpellChecker.Native;
using DevExpress.XtraSpellChecker.Parser;
using DevExpress.XtraSpellChecker;
using DevExpress.Services.Implementation;
using DevExpress.Services;
using DevExpress.XtraRichEdit.Export.Rtf;
using DevExpress.Data.Mask;
using DevExpress.Utils.KeyboardHandler;
using DevExpress.Utils.Design;
using DevExpress.Data.XtraReports.Wizard.Native;
using DevExpress.Data.XtraReports.Wizard;
using DevExpress.Data.XtraReports.ServiceModel.DataContracts;
using DevExpress.Data.XtraReports.ServiceModel;
using DevExpress.XtraReports.Parameters;
using DevExpress.Data.XtraReports.Native;
using DevExpress.Data.XtraReports.Labels;
using DevExpress.Data.XtraReports.DataProviders;
using DevExpress.XtraReports.Design.Commands;
using DevExpress.XtraReports.UserDesigner;
using DevExpress.XtraReports.Native.Parameters;
using DevExpress.XtraReports.UI;
using DevExpress.Data.WizardFramework;
using DevExpress.Utils.About;
using DevExpress.Data.Utils.ServiceModel;
using DevExpress.Utils.IoC;
using DevExpress.Xpf.Printing;
using DevExpress.XtraPrinting.Native;
using DevExpress.Utils.OAuth.Provider;
using DevExpress.Utils.OAuth;
using DevExpress.Utils.Gac;
using DevExpress.XtraGrid;
using DevExpress.Data.Filtering.Exceptions;
using DevExpress.Xpo;
using DevExpress.Utils.Extensions.Helpers;
using DevExpress.Data.Details;
using DevExpress.Xpo.Exceptions;
using DevExpress.Xpo.DB.Exceptions;
using DevExpress.Xpo.Helpers;
using DevExpress.Xpo.DB;
using DevExpress.Xpo.DB.Helpers;
using DevExpress.Data.Storage;
using DevExpress.Data.Access;
using DevExpress.Utils.Menu;
using DevExpress.Utils.Commands;
using DevExpress.Data.Filtering;
using DevExpress.Data.Helpers;
using DevExpress.Data.Selection;
using DevExpress.XtraReports.Native;
using DevExpress.XtraReports.Native.Data;
using DevExpress.Data.Browsing.Design;
using DevExpress.XtraReports.Design;
using DevExpress.Data;
using DevExpress.Services.Internal;
using DevExpress.Data.Browsing;
using DevExpress.Data.Filtering.Helpers;
using DevExpress.Data.Native;
using DevExpress.Utils;
using Cryptdll.classi;
using Cryptdll;
using MRG.Controls.UI;
using BusinessObjects.ERP.Variants.Documents.Variants;
using BusinessObjects.ERP.BillOfMaterials.Documents.BOMNavigation;
using BusinessObjects.Doors.Doors.DynamicDocuments.DoorsConf;
using BusinessObjects.Doors.Doors.DynamicDocuments.Configurazioni;
using BusinessObjects.Doors.Doors.DynamicDocuments.ConfiguratoreDoors;
using Microarea.Library.WCFGeneratedFunctions;
using System.Collections.Generic;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.OleDb;
using Microarea.EasyBuilder;
using Microarea.EasyBuilder.MVC;
using Microarea.TaskBuilderNet.UI.WinControls;
using Microarea.TaskBuilderNet.Interfaces.View;
using Microarea.TaskBuilderNet.Interfaces;
using Microarea.TaskBuilderNet.Core.CoreTypes;
using Microarea.TaskBuilderNet.Core.EasyBuilder;
using Microarea.TaskBuilderNet.Core.Generic;
using Microarea.Framework.TBApplicationWrapper;
using Microarea.TaskBuilderNet.Interfaces.Model;
using System.ComponentModel;
using System.Windows.Forms;
using System.Xml;
using System.Drawing;
using System.Data;
using System;
namespace Customization.ERP.SaleOrders.Documents.SaleOrd.SaleOrd
{
	public class TDMDOORSMaggiorazioni_TAG_DOORS_Maggiorazioni : Microarea.Framework.TBApplicationWrapper.MSqlRecord
	{
		public TDMDOORSMaggiorazioni_TAG_DOORS_Maggiorazioni(System.IntPtr wrappedObject) : base(wrappedObject)
		{
		}

		public MDataDate fld_TBCreated;

		public MDataDate fld_TBModified;

		public MDataLng fld_TBCreatedID;

		public MDataLng fld_TBModifiedID;

		public MDataGuid fld_TBGuid;

		public MDataStr fld_Prodctg;

		public MDataStr fld_ProdSubCtg;

		public MDataStr fld_Customer;

		public MDataStr fld_DescriTabella;

		public MDataPerc fld_Sconto1;

		public MDataPerc fld_Sconto2;

		public MDataPerc fld_Sconto3;

		public MDataPerc fld_Provvigione;

		public MDataPerc fld_ScontoMagg1;

		public MDataPerc fld_ScontoMagg2;

		public MDataPerc fld_ScontoMagg3;

		public override void CreateComponents()
		{
			fld_TBCreated = new Microarea.Framework.TBApplicationWrapper.MDataDate(this.GetFieldPtr("TBCreated"));
			this.Add(fld_TBCreated, false);
			fld_TBModified = new Microarea.Framework.TBApplicationWrapper.MDataDate(this.GetFieldPtr("TBModified"));
			this.Add(fld_TBModified, false);
			fld_TBCreatedID = new Microarea.Framework.TBApplicationWrapper.MDataLng(this.GetFieldPtr("TBCreatedID"));
			this.Add(fld_TBCreatedID, false);
			fld_TBModifiedID = new Microarea.Framework.TBApplicationWrapper.MDataLng(this.GetFieldPtr("TBModifiedID"));
			this.Add(fld_TBModifiedID, false);
			fld_TBGuid = new Microarea.Framework.TBApplicationWrapper.MDataGuid(this.GetFieldPtr("TBGuid"));
			this.Add(fld_TBGuid, false);
			fld_Prodctg = new Microarea.Framework.TBApplicationWrapper.MDataStr(this.GetFieldPtr("Prodctg"));
			this.Add(fld_Prodctg, false);
			fld_ProdSubCtg = new Microarea.Framework.TBApplicationWrapper.MDataStr(this.GetFieldPtr("ProdSubCtg"));
			this.Add(fld_ProdSubCtg, false);
			fld_Customer = new Microarea.Framework.TBApplicationWrapper.MDataStr(this.GetFieldPtr("Customer"));
			this.Add(fld_Customer, false);
			fld_DescriTabella = new Microarea.Framework.TBApplicationWrapper.MDataStr(this.GetFieldPtr("DescriTabella"));
			this.Add(fld_DescriTabella, false);
			fld_Sconto1 = new Microarea.Framework.TBApplicationWrapper.MDataPerc(this.GetFieldPtr("Sconto1"));
			this.Add(fld_Sconto1, false);
			fld_Sconto2 = new Microarea.Framework.TBApplicationWrapper.MDataPerc(this.GetFieldPtr("Sconto2"));
			this.Add(fld_Sconto2, false);
			fld_Sconto3 = new Microarea.Framework.TBApplicationWrapper.MDataPerc(this.GetFieldPtr("Sconto3"));
			this.Add(fld_Sconto3, false);
			fld_Provvigione = new Microarea.Framework.TBApplicationWrapper.MDataPerc(this.GetFieldPtr("Provvigione"));
			this.Add(fld_Provvigione, false);
			fld_ScontoMagg1 = new Microarea.Framework.TBApplicationWrapper.MDataPerc(this.GetFieldPtr("ScontoMagg1"));
			this.Add(fld_ScontoMagg1, false);
			fld_ScontoMagg2 = new Microarea.Framework.TBApplicationWrapper.MDataPerc(this.GetFieldPtr("ScontoMagg2"));
			this.Add(fld_ScontoMagg2, false);
			fld_ScontoMagg3 = new Microarea.Framework.TBApplicationWrapper.MDataPerc(this.GetFieldPtr("ScontoMagg3"));
			this.Add(fld_ScontoMagg3, false);
		}

		public override void ApplyResources()
		{
			Microarea.EasyBuilder.CustomizationComponentResourceManager resources = Strings.ResourceManager;
		}

		public override void ClearComponents()
		{
			base.ClearComponents();
			fld_TBCreated = null;
			fld_TBModified = null;
			fld_TBCreatedID = null;
			fld_TBModifiedID = null;
			fld_TBGuid = null;
			fld_Prodctg = null;
			fld_ProdSubCtg = null;
			fld_Customer = null;
			fld_DescriTabella = null;
			fld_Sconto1 = null;
			fld_Sconto2 = null;
			fld_Sconto3 = null;
			fld_Provvigione = null;
			fld_ScontoMagg1 = null;
			fld_ScontoMagg2 = null;
			fld_ScontoMagg3 = null;
		}
	}
}
