using System.Threading.Channels;
using System.Text.Json.Serialization;
using System.Text.Json;
using System.Text.Encodings.Web;
using System.Text.Unicode;
using System.Numerics;
using System.Buffers.Binary;
using System.Buffers.Text;
using System.IO.Pipelines;
using System.Runtime.InteropServices;
using System.IO.MemoryMappedFiles;
using System.Threading;
using System.IO.Pipes;
using System.IO;
using System.Diagnostics.PerformanceData;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Dynamic;
using System.Security.Cryptography.X509Certificates;
using System.Security.Cryptography;
using System.Security;
using Microsoft.Win32.SafeHandles;
using System.Linq;
using System.Diagnostics.Eventing.Reader;
using System.Management.Instrumentation;
using System.Diagnostics.Eventing;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Buffers;
using RestSharp.Validation;
using RestSharp.Serializers;
using RestSharp.Contrib;
using RestSharp.Extensions;
using RestSharp.Deserializers;
using RestSharp.Authenticators.OAuth;
using RestSharp.Authenticators;
using RestSharp;
using OpenCartGateClasses;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Schema;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json;
using Microsoft.Extensions.Primitives;
using Microsoft.Extensions.Options;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Configuration.Memory;
using Microsoft.Extensions.Configuration;
using System.Threading.Tasks.Sources;
using System.Threading.Tasks;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.SignalR.Protocol;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.AspNetCore.Http.Features.Authentication;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Connections;
using Microsoft.AspNetCore.Http.Connections.Client;
using Microsoft.AspNetCore.Connections.Features;
using Microsoft.AspNetCore.Connections;
using ElaboratoreOrdiniClasses;
using DoorsAddoOnLibrary.Models;
using DoorsAddoOnLibrary.BillOfMaterialsComponents;
using DoorsAddoOnLibrary.LoginManager;
using DoorsAddoOnLibrary.TbServices;
using DoorsAddoOnLibrary;
using DevExpress.XtraVerticalGrid.Utils;
using DevExpress.XtraVerticalGrid.ViewInfo;
using DevExpress.XtraVerticalGrid.Events;
using DevExpress.XtraVerticalGrid.Editors;
using DevExpress.XtraVerticalGrid.Painters;
using DevExpress.XtraVerticalGrid.Localization;
using DevExpress.XtraVerticalGrid.Internal;
using DevExpress.XtraVerticalGrid.Design;
using DevExpress.XtraVerticalGrid.Data;
using DevExpress.XtraVerticalGrid.Rows;
using DevExpress.XtraVerticalGrid.Blending;
using DevExpress.XtraVerticalGrid;
using DevExpress.XtraVerticalGrid.Accessibility;
using DevExpress.XtraTreeList.Printing;
using DevExpress.XtraTreeList.ViewInfo;
using DevExpress.XtraTreeList.Menu;
using DevExpress.XtraTreeList.Helpers;
using DevExpress.XtraTreeList.Handler;
using DevExpress.XtraTreeList.Painter;
using DevExpress.XtraTreeList.Data;
using DevExpress.XtraTreeList.StyleFormatConditions;
using DevExpress.XtraTreeList.Scrolling;
using DevExpress.XtraTreeList.Frames;
using DevExpress.XtraTreeList.Design;
using DevExpress.XtraTreeList.Localization;
using DevExpress.XtraTreeList.Internal;
using DevExpress.XtraTreeList.Columns;
using DevExpress.XtraTreeList.FilterEditor;
using DevExpress.XtraTreeList.Nodes.Operations;
using DevExpress.XtraTreeList.Native;
using DevExpress.XtraTreeList.Nodes;
using DevExpress.XtraTreeList.Dragging;
using DevExpress.XtraTreeList.Accessibility;
using DevExpress.XtraTreeList.Blending;
using DevExpress.XtraTreeList;
using DevExpress.XtraEditors.Controls.Rtf;
using DevExpress.XtraFilterEditor.IntelliSense;
using DevExpress.XtraFilterEditor;
using DevExpress.XtraRichEdit.Painters;
using DevExpress.XtraRichEdit.Forms.Design;
using DevExpress.XtraRichEdit.API.RichTextBox;
using DevExpress.XtraRichEdit.API.Word;
using DevExpress.API.Mso;
using DevExpress.XtraPrinting.Preview.Native.Galleries;
using DevExpress.XtraPrinting.Preview.Native;
using DevExpress.XtraPrinting.Links;
using DevExpress.XtraPrinting.Control;
using DevExpress.XtraPrinting.Control.Native;
using DevExpress.XtraPrinting.CodedUISupport;
using DevExpress.XtraPrinting.Native.WinControls;
using DevExpress.XtraLayout.Tab;
using DevExpress.XtraLayout.Scrolling;
using DevExpress.XtraLayout.Registrator;
using DevExpress.XtraLayout.Localization;
using DevExpress.XtraLayout.Converter;
using DevExpress.XtraLayout.Printing;
using DevExpress.XtraLayout.Dragging;
using DevExpress.XtraLayout.Diagnostics;
using DevExpress.XtraDataLayout;
using DevExpress.XtraLayout.Helpers;
using DevExpress.XtraDashboardLayout;
using DevExpress.XtraLayout.Customization.Controls;
using DevExpress.XtraLayout.Utils;
using DevExpress.XtraLayout.Accessibility;
using DevExpress.XtraLayout.ViewInfo;
using DevExpress.XtraLayout.Painting;
using DevExpress.XtraLayout.HitInfo;
using DevExpress.XtraLayout.Customization;
using DevExpress.XtraLayout.Resizing;
using DevExpress.XtraLayout;
using DevExpress.XtraLayout.Handlers;
using DevExpress.XtraLayout.Adapters;
using DevExpress.XtraGrid.Repository;
using DevExpress.XtraGrid.Tab;
using DevExpress.XtraGrid.Filter.Parser;
using DevExpress.XtraGrid.Menu;
using DevExpress.XtraGrid.Filter;
using DevExpress.XtraGrid.Printing;
using DevExpress.XtraGrid.Editors;
using DevExpress.XtraGrid.Frames;
using DevExpress.XtraGrid.Registrator;
using DevExpress.XtraGrid.Views.Layout.Printing;
using DevExpress.XtraGrid.Views.Layout.Drawing;
using DevExpress.XtraGrid.Views.Layout.Modes;
using DevExpress.XtraGrid.Views.Layout.Customization;
using DevExpress.XtraGrid.Views.Layout.Events;
using DevExpress.XtraGrid.Views.Layout.ViewInfo;
using DevExpress.XtraGrid.Views.Layout.Frames;
using DevExpress.XtraGrid.Views.Layout.Handler;
using DevExpress.XtraGrid.Views.Layout.Designer;
using DevExpress.XtraGrid.Views.Layout;
using DevExpress.XtraGrid.GroupSummaryEditor;
using DevExpress.XtraGrid.Localization;
using DevExpress.XtraGrid.Drawing;
using DevExpress.XtraGrid.Internal;
using DevExpress.XtraGrid.FilterEditor;
using DevExpress.XtraGrid.Export;
using DevExpress.XtraGrid.Views.Card.ViewInfo;
using DevExpress.XtraGrid.Views.Card.Drawing;
using DevExpress.XtraGrid.Views.Card.Handler;
using DevExpress.XtraGrid.Views.Card;
using DevExpress.XtraGrid.Design;
using DevExpress.XtraGrid.Blending;
using DevExpress.XtraGrid.Helpers;
using DevExpress.XtraGrid.Controls;
using DevExpress.XtraGrid.Views.Printing;
using DevExpress.XtraGrid.Scrolling;
using DevExpress.XtraGrid.Accessibility;
using DevExpress.XtraGrid.Views.BandedGrid.Customization;
using DevExpress.XtraGrid.Views.Grid.Customization;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Skins;
using DevExpress.XtraGrid.Views.BandedGrid.ViewInfo;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using DevExpress.XtraGrid.Views.Base.ViewInfo;
using DevExpress.XtraGrid.Views.BandedGrid.Drawing;
using DevExpress.XtraGrid.Views.Grid.Drawing;
using DevExpress.XtraGrid.Views.BandedGrid;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.Base.Handler;
using DevExpress.XtraGrid.Views.Grid.Handler;
using DevExpress.XtraGrid.Views.BandedGrid.Handler;
using DevExpress.XtraGrid.Dragging;
using DevExpress.XtraEditors.FeatureBrowser;
using DevExpress.XtraTab.Buttons;
using DevExpress.XtraTab.Registrator;
using DevExpress.XtraTab.Drawing;
using DevExpress.XtraTab.ViewInfo;
using DevExpress.Accessibility.Tab;
using DevExpress.XtraWaitForm;
using DevExpress.XtraSplashForm;
using DevExpress.XtraSplashScreen;
using DevExpress.XtraEditors.Registrator;
using DevExpress.XtraEditors.Internal;
using DevExpress.XtraPivotGrid;
using DevExpress.XtraTab;
using DevExpress.XtraEditors.ColorPickEditControl;
using DevExpress.XtraEditors.Calendar;
using DevExpress.XtraEditors.NavigatorButtons;
using DevExpress.XtraEditors.Mask;
using DevExpress.XtraEditors.Popup;
using DevExpress.XtraEditors.Helpers;
using DevExpress.XtraEditors.Design;
using DevExpress.XtraEditors.Frames;
using DevExpress.XtraEditors.Customization;
using DevExpress.XtraEditors.ListControls;
using DevExpress.XtraEditors.Container;
using DevExpress.XtraEditors.CodedUISupport;
using DevExpress.XtraEditors.ButtonPanel;
using DevExpress.XtraEditors.Senders;
using DevExpress.XtraEditors.Persistent;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraBars.Ribbon.Customization;
using DevExpress.XtraBars.Docking.Controller;
using DevExpress.XtraBars.Docking2010.Dragging.WindowsUI;
using DevExpress.XtraBars.Docking2010.Views.NoDocuments;
using DevExpress.XtraBars.Docking2010.Views.NativeMdi;
using DevExpress.XtraBars.Docking2010.Views.WindowsUI;
using DevExpress.XtraBars.Commands.Internal;
using DevExpress.XtraBars.Commands.Ribbon;
using DevExpress.XtraBars.Commands;
using DevExpress.XtraBars.Commands.Design;
using DevExpress.XtraEditors.ColorPick.Popup.Galleries;
using DevExpress.XtraBars.ColorPick.Popup;
using DevExpress.XtraEditors.ColorPick.Picker;
using DevExpress.XtraBars.CodedUISupport;
using DevExpress.XtraBars.Editors;
using DevExpress.XtraTabbedMdi;
using DevExpress.XtraBars.Ribbon.Helpers;
using DevExpress.XtraBars.Ribbon.Internal;
using DevExpress.XtraBars.Ribbon.Gallery;
using DevExpress.XtraBars.Styles;
using DevExpress.XtraBars.Ribbon.Drawing;
using DevExpress.XtraBars.Ribbon.ViewInfo;
using DevExpress.XtraBars.Ribbon.Handler;
using DevExpress.XtraBars.Ribbon.Accessible;
using DevExpress.XtraBars.Localization;
using DevExpress.XtraBars.Design;
using DevExpress.XtraBars.Docking2010.Customization;
using DevExpress.XtraBars.InternalItems;
using DevExpress.XtraBars.Docking.Paint;
using DevExpress.XtraBars.Docking.Helpers;
using DevExpress.XtraBars.Docking;
using DevExpress.XtraBars.Docking2010.Dragging;
using DevExpress.XtraBars.Docking2010;
using DevExpress.XtraBars.Docking2010.DragEngine;
using DevExpress.XtraBars.Docking2010.Views.Tabbed;
using DevExpress.XtraBars.Docking2010.Views;
using DevExpress.XtraBars.Docking2010.Base;
using DevExpress.XtraBars.Ribbon;
using DevExpress.XtraBars.Customization.Helpers;
using DevExpress.XtraBars.Helpers.Docking;
using DevExpress.XtraBars.Forms;
using DevExpress.XtraBars.Registration;
using DevExpress.XtraBars.Helpers;
using DevExpress.XtraBars.ViewInfo;
using DevExpress.XtraBars.Objects;
using DevExpress.XtraBars.Native;
using DevExpress.XtraBars.MessageFilter;
using DevExpress.XtraBars.Painters;
using DevExpress.XtraBars.Utils;
using DevExpress.XtraBars;
using DevExpress.XtraBars.Controls;
using DevExpress.XtraBars.Alerter;
using DevExpress.XtraBars.Customization;
using DevExpress.XtraBars.Accessible;
using DevExpress.Utils.UI.Localization;
using DevExpress.Utils.UI;
using DevExpress.Utils.Frames;
using DevExpress.Utils.WXPaint;
using DevExpress.Utils.Mdi;
using DevExpress.Utils.Registrator;
using DevExpress.Utils.Native;
using DevExpress.Skins.Info;
using DevExpress.Skins.XtraForm;
using DevExpress.UserSkins;
using DevExpress.XtraReports.Serialization;
using DevExpress.XtraEditors.ViewInfo;
using DevExpress.Utils.NonclientArea;
using DevExpress.Utils.Drawing.Helpers;
using DevExpress.Utils.Helpers;
using DevExpress.Utils.Paint;
using DevExpress.LookAndFeel.Design;
using DevExpress.LookAndFeel.Helpers;
using DevExpress.Utils.Win.Hook;
using DevExpress.Utils.ViewInfo;
using DevExpress.Utils.ToolTip.ViewInfo;
using DevExpress.Utils.Extensions;
using DevExpress.XtraEditors.ScrollHelpers;
using DevExpress.Utils.Win;
using DevExpress.Utils.DragDrop;
using DevExpress.Skins;
using DevExpress.Utils.Gesture;
using DevExpress.Utils.Compress;
using DevExpress.Utils.CodedUISupport;
using DevExpress.Utils.Drawing;
using DevExpress.Utils.Drawing.Animation;
using DevExpress.Accessibility;
using DevExpress.LookAndFeel;
using DevExpress.XtraEditors.Drawing;
using DevExpress.XtraRichEdit.Internal.SimpleLayout;
using DevExpress.XtraRichEdit.Internal.ReadingLayout;
using DevExpress.XtraRichEdit.Internal.DraftLayout;
using DevExpress.XtraRichEdit.Internal.PrintLayout;
using DevExpress.XtraRichEdit.Design;
using DevExpress.XtraRichEdit.SyntaxEdit.Commands.Internal;
using DevExpress.XtraRichEdit.SyntaxEdit.Commands;
using DevExpress.XtraRichEdit.SyntaxEdit;
using DevExpress.XtraRichEdit.SyntaxEdit.Services.Implementation;
using DevExpress.XtraRichEdit.SpellChecker;
using DevExpress.XtraRichEdit.Services.Implementation;
using DevExpress.XtraRichEdit.Ruler;
using DevExpress.XtraPrinting.Native.RichText;
using DevExpress.XtraPrinting.Exports;
using DevExpress.XtraRichEdit.Printing;
using DevExpress.XtraRichEdit.Utils.NumberConverters;
using DevExpress.XtraRichEdit.Mouse;
using DevExpress.XtraRichEdit.Localization.Internal;
using DevExpress.XtraRichEdit.Localization;
using DevExpress.XtraRichEdit.Keyboard;
using DevExpress.XtraRichEdit.Design.Internal;
using DevExpress.XtraRichEdit.Menu;
using DevExpress.XtraRichEdit.Forms;
using DevExpress.XtraRichEdit.Fields.Expression;
using DevExpress.XtraRichEdit.Fields;
using DevExpress.XtraRichEdit.Model.History;
using DevExpress.XtraRichEdit.Layout.TableLayout;
using DevExpress.XtraRichEdit.Layout.Engine;
using DevExpress.XtraRichEdit.Layout.Export;
using DevExpress.XtraRichEdit.Import.Xaml;
using DevExpress.XtraRichEdit.Export.Xaml;
using DevExpress.XtraRichEdit.Import.WordML;
using DevExpress.XtraRichEdit.Export.WordML;
using DevExpress.XtraRichEdit.Import.Rtf.Tables;
using DevExpress.XtraRichEdit.Import.Rtf;
using DevExpress.XtraRichEdit.Export.PlainText;
using DevExpress.XtraRichEdit.Import.OpenXml;
using DevExpress.XtraRichEdit.Export.OpenXml;
using DevExpress.XtraRichEdit.Import.OpenDocument;
using DevExpress.XtraRichEdit.Export.OpenDocument;
using DevExpress.XtraRichEdit.Import.Mht;
using DevExpress.XtraRichEdit.Export.Mht;
using DevExpress.XtraRichEdit.Import.Html;
using DevExpress.XtraRichEdit.Import.EPub;
using DevExpress.XtraRichEdit.Export.Html;
using DevExpress.XtraRichEdit.Export.EPub;
using DevExpress.XtraRichEdit.Services;
using DevExpress.XtraRichEdit.Import;
using DevExpress.XtraRichEdit.Import.Doc;
using DevExpress.XtraRichEdit.Tables.Native;
using DevExpress.XtraRichEdit.Export.Doc;
using DevExpress.XtraRichEdit.Native;
using DevExpress.XtraRichEdit.Export;
using DevExpress.XtraRichEdit.Utils;
using DevExpress.XtraRichEdit.Commands.Helper;
using DevExpress.XtraRichEdit.Commands.Internal;
using DevExpress.XtraRichEdit.Commands;
using DevExpress.XtraRichEdit.Drawing;
using DevExpress.XtraRichEdit.Layout;
using DevExpress.XtraRichEdit.Internal;
using DevExpress.XtraRichEdit.API.Native.Implementation;
using DevExpress.XtraRichEdit.API.Native;
using DevExpress.XtraRichEdit.API.Internal;
using DevExpress.XtraRichEdit.Model;
using DevExpress.Printing.ServiceModel.DataContracts;
using DevExpress.Xpf.Printing.ServiceModel.DataContracts;
using DevExpress.XtraReports.ServiceModel.DataContracts;
using DevExpress.XtraPrinting.Drawing;
using DevExpress.XtraPrinting.Preview;
using DevExpress.Printing;
using DevExpress.XtraReports;
using DevExpress.XtraPrinting.InternalAccess;
using DevExpress.XtraPrinting.Export.Pdf.Compression;
using System.Collections;
using DevExpress.XtraPrinting.Native.LayoutAdjustment;
using DevExpress.XtraPrinting.Native.TextRotation;
using DevExpress.XtraPrinting.Native.Navigation;
using DevExpress.XtraPrinting.Native.Lines;
using DevExpress.XtraPrinting.HtmlExport;
using DevExpress.XtraPrinting.HtmlExport.Native;
using DevExpress.XtraPrinting.Export.XLS;
using DevExpress.XtraPrinting.Export.Text;
using DevExpress.XtraPrinting.Export.Rtf;
using DevExpress.XtraPrinting.Export.Imaging;
using DevExpress.XtraPrinting.Native.ExportOtions;
using DevExpress.XtraPrinting.Native.ExportOptionsControllers;
using DevExpress.XtraPrinting.Shape;
using DevExpress.XtraPrinting.Shape.Native;
using DevExpress.XtraPrinting.NativeBricks;
using DevExpress.XtraPrinting.Export.Pdf;
using DevExpress.XtraPrinting.Export;
using DevExpress.Printing.Core.Native;
using DevExpress.Printing.Core;
using DevExpress.XtraPrintingLinks;
using DevExpress.Printing.Core.HtmlExport;
using DevExpress.XtraPrinting.Export.Web;
using DevExpress.XtraPrinting.HtmlExport.Controls;
using DevExpress.XtraPrinting.BarCode.Native;
using DevExpress.XtraPrinting.BarCode;
using DevExpress.XtraPrinting.BrickExporters;
using DevExpress.Office.Services;
using DevExpress.Office.Services.Implementation;
using DevExpress.Office.Layout.Export;
using DevExpress.Office.Printing;
using DevExpress.Office.PInvoke;
using DevExpress.Office.Localization.Internal;
using DevExpress.Office.Localization;
using DevExpress.Office.Drawing;
using DevExpress.XtraRichEdit;
using DevExpress.Office.History;
using DevExpress.Office.Model;
using DevExpress.Office.Layout;
using DevExpress.Utils.StructuredStorage.Writer;
using DevExpress.Utils.StructuredStorage.Internal.Writer;
using DevExpress.Utils.StructuredStorage.Internal.Reader;
using DevExpress.Utils.StructuredStorage.Reader;
using DevExpress.Utils.StructuredStorage.Internal;
using DevExpress.Office.Utils;
using DevExpress.Office.Import;
using DevExpress.Office.Export;
using DevExpress.Office;
using DevExpress.Office.Internal;
using DevExpress.Office.API.Internal;
using DevExpress.Data.XtraReports.Wizard.Views;
using DevExpress.Data.XtraReports.Wizard.Presenters;
using DevExpress.Utils.Implementation;
using DevExpress.Data.Summary;
using DevExpress.Data.Async.Helpers;
using DevExpress.Schedule.Serializing;
using DevExpress.Schedule;
using DevExpress.Utils.Text.Internal;
using DevExpress.Data.Async;
using DevExpress.Data.Printing.Native;
using DevExpress.Utils.Zip;
using DevExpress.XtraPrinting.Localization;
using DevExpress.XtraPrinting.DataNodes;
using DevExpress.Data.ChartDataSources;
using DevExpress.Charts.Native;
using DevExpress.Xpo.Logger.Transport;
using DevExpress.Xpo.Logger;
using DevExpress.Utils.Text;
using DevExpress.XtraEditors.Filtering;
using DevExpress.XtraEditors;
using DevExpress.Data.ExpressionEditor;
using DevExpress.XtraExport;
using DevExpress.Data.Linq.Helpers;
using DevExpress.Data.Linq;
using DevExpress.Utils.Internal;
using DevExpress.Xpo.Providers;
using DevExpress.Data.Db;
using DevExpress.Data.Design;
using DevExpress.Xpo.XtraData;
using DevExpress.Data.Utils.ServiceModel.Native;
using DevExpress.CodeParser;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.DXErrorProvider;
using DevExpress.XtraPrinting;
using DevExpress.Internal;
using DevExpress.XtraPrinting.Design;
using DevExpress.Utils.Serializing.Helpers;
using DevExpress.Utils.Editors;
using DevExpress.Utils.Localization.Internal;
using DevExpress.Utils.Localization;
using DevExpress.Data.Utils;
using DevExpress.Utils.Serializing;
using DevExpress.WebUtils;
using DevExpress.Utils.Controls;
using DevExpress.Data.IO;
using DevExpress.XtraSpellChecker.Native;
using DevExpress.XtraSpellChecker.Parser;
using DevExpress.XtraSpellChecker;
using DevExpress.Services.Implementation;
using DevExpress.Services;
using DevExpress.XtraRichEdit.Export.Rtf;
using DevExpress.Data.Mask;
using DevExpress.Utils.KeyboardHandler;
using DevExpress.Utils.Design;
using DevExpress.Data.XtraReports.Wizard.Native;
using DevExpress.Data.XtraReports.Wizard;
using DevExpress.Data.XtraReports.ServiceModel.DataContracts;
using DevExpress.Data.XtraReports.ServiceModel;
using DevExpress.XtraReports.Parameters;
using DevExpress.Data.XtraReports.Native;
using DevExpress.Data.XtraReports.Labels;
using DevExpress.Data.XtraReports.DataProviders;
using DevExpress.XtraReports.Design.Commands;
using DevExpress.XtraReports.UserDesigner;
using DevExpress.XtraReports.Native.Parameters;
using DevExpress.XtraReports.UI;
using DevExpress.Data.WizardFramework;
using DevExpress.Utils.About;
using DevExpress.Data.Utils.ServiceModel;
using DevExpress.Utils.IoC;
using DevExpress.Xpf.Printing;
using DevExpress.XtraPrinting.Native;
using DevExpress.Utils.OAuth.Provider;
using DevExpress.Utils.OAuth;
using DevExpress.Utils.Gac;
using DevExpress.XtraGrid;
using DevExpress.Data.Filtering.Exceptions;
using DevExpress.Xpo;
using DevExpress.Utils.Extensions.Helpers;
using DevExpress.Data.Details;
using DevExpress.Xpo.Exceptions;
using DevExpress.Xpo.DB.Exceptions;
using DevExpress.Xpo.Helpers;
using DevExpress.Xpo.DB;
using DevExpress.Xpo.DB.Helpers;
using DevExpress.Data.Storage;
using DevExpress.Data.Access;
using DevExpress.Utils.Menu;
using DevExpress.Utils.Commands;
using DevExpress.Data.Filtering;
using DevExpress.Data.Helpers;
using DevExpress.Data.Selection;
using DevExpress.XtraReports.Native;
using DevExpress.XtraReports.Native.Data;
using DevExpress.Data.Browsing.Design;
using DevExpress.XtraReports.Design;
using DevExpress.Data;
using DevExpress.Services.Internal;
using DevExpress.Data.Browsing;
using DevExpress.Data.Filtering.Helpers;
using DevExpress.Data.Native;
using DevExpress.Utils;
using Cryptdll.classi;
using Cryptdll;
using MRG.Controls.UI;
using Microarea.Library.WCFGeneratedFunctions;
using System.Collections.Generic;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.OleDb;
using Microarea.EasyBuilder;
using Microarea.EasyBuilder.MVC;
using Microarea.TaskBuilderNet.UI.WinControls;
using Microarea.TaskBuilderNet.Interfaces.View;
using Microarea.TaskBuilderNet.Interfaces;
using Microarea.TaskBuilderNet.Core.CoreTypes;
using Microarea.TaskBuilderNet.Core.EasyBuilder;
using Microarea.TaskBuilderNet.Core.Generic;
using Microarea.Framework.TBApplicationWrapper;
using Microarea.TaskBuilderNet.Interfaces.Model;
using System.ComponentModel;
using System.Windows.Forms;
using System.Xml;
using System.Drawing;
using System.Data;
using System;
namespace Customization.Doors.Doors.DynamicDocuments.Parametri.Parametri
{
	public class TileMTileDialog1 : Microarea.Framework.TBApplicationWrapper.MTileDialog
	{
		public TileMTileDialog1(Microarea.TaskBuilderNet.Interfaces.View.IWindowWrapperContainer parentWindow, string controlName, string controlClass, System.Drawing.Point location, bool hasCodeBehind) : base(parentWindow, controlName, controlClass, location, hasCodeBehind)
		{
		}

		[Microarea.TaskBuilderNet.Core.EasyBuilder.PreserveFieldAttribute]
		public new MDParametri Document
		{
			get
			{
				return (MDParametri)DocumentController.controller.Document;
			}
		}

		public MParsedStatic ctrl_Description;

		public MParsedStatic ctrl_Description1;

		public MParsedStatic ctrl_Description10;

		public MParsedStatic ctrl_Description2;

		public MParsedStatic ctrl_Description3;

		public MParsedStatic ctrl_Description4;

		public MParsedStatic ctrl_Description5;

		public MParsedStatic ctrl_Description6;

		public MParsedStatic ctrl_Description7;

		public MParsedStatic ctrl_Description8;

		public MParsedStatic ctrl_Description9;

		public GenericGroupBox ctrl_IDC_STATIC_AREA;

		public MParsedEdit ctrl_CatMercImbotti;

		public MParsedEdit ctrl_CatMercPorte;

		public MParsedEdit ctrl_CatMercTelai;

		public MParsedEdit ctrl_CatMercPannelli;

		public MParsedEdit ctrl_CatMercAccessori;

		public MParsedEdit ctrl_CatMercPanneliLav;

		public MParsedEdit ctrl_CatMercTelaiLav;

		public MParsedEdit ctrl_CatMercCoprifiliLav;

		public MParsedEdit ctrl_CatMercCfAlettaLunga;

		public MParsedEdit ctrl_CatMercFerramenta;

		public MParsedEdit ctrl_CatMercVetri;

		public override void CreateComponents()
		{
			ctrl_Description = new Microarea.Framework.TBApplicationWrapper.MParsedStatic(this, "Description", "StringStatic", new System.Drawing.Point(376, 52), false);
			ctrl_Description.DataBinding = new FieldDataBinding(Document.HKLCommodityCtg.TMA_CommodityCtg.fld_Description, Document.HKLCommodityCtg);
			ctrl_Description.AddChangedProperty("Caption");
			ctrl_Description.Border = true;
			ctrl_Description.AddChangedProperty("Border");
			ctrl_Description.Size = new System.Drawing.Size(240, 23);
			ctrl_Description.AddChangedProperty("Size");
			MLabelProperties ctrl_Description_MLabelProperties = (MLabelProperties)ctrl_Description.Extensions["MLabelProperties"];
			ctrl_Description_MLabelProperties.Sunken = true;
			ctrl_Description_MLabelProperties.AddChangedProperty("Sunken");
			this.Add(ctrl_Description, true);
			ctrl_Description1 = new Microarea.Framework.TBApplicationWrapper.MParsedStatic(this, "Description1", "StringStatic", new System.Drawing.Point(376, 98), false);
			ctrl_Description1.DataBinding = new FieldDataBinding(Document.HKLCommodityCtgPorte.TMA_CommodityCtg.fld_Description, Document.HKLCommodityCtgPorte);
			ctrl_Description1.AddChangedProperty("Caption");
			ctrl_Description1.Border = true;
			ctrl_Description1.AddChangedProperty("Border");
			ctrl_Description1.Size = new System.Drawing.Size(240, 23);
			ctrl_Description1.AddChangedProperty("Size");
			MLabelProperties ctrl_Description1_MLabelProperties = (MLabelProperties)ctrl_Description1.Extensions["MLabelProperties"];
			ctrl_Description1_MLabelProperties.Sunken = true;
			ctrl_Description1_MLabelProperties.AddChangedProperty("Sunken");
			this.Add(ctrl_Description1, true);
			ctrl_Description10 = new Microarea.Framework.TBApplicationWrapper.MParsedStatic(this, "Description10", "StringStatic", new System.Drawing.Point(375, 519), false);
			ctrl_Description10.DataBinding = new FieldDataBinding(Document.HKLCommodityCtgVetri.TMA_CommodityCtg.fld_Description, Document.HKLCommodityCtgVetri);
			ctrl_Description10.AddChangedProperty("DataBinding");
			ctrl_Description10.AddChangedProperty("Caption");
			ctrl_Description10.Border = true;
			ctrl_Description10.AddChangedProperty("Border");
			ctrl_Description10.Size = new System.Drawing.Size(239, 23);
			ctrl_Description10.AddChangedProperty("Size");
			MLabelProperties ctrl_Description10_MLabelProperties = (MLabelProperties)ctrl_Description10.Extensions["MLabelProperties"];
			ctrl_Description10_MLabelProperties.Sunken = true;
			ctrl_Description10_MLabelProperties.AddChangedProperty("Sunken");
			this.Add(ctrl_Description10, true);
			ctrl_Description2 = new Microarea.Framework.TBApplicationWrapper.MParsedStatic(this, "Description2", "StringStatic", new System.Drawing.Point(377, 142), false);
			ctrl_Description2.DataBinding = new FieldDataBinding(Document.HKLCommodityCtgTelai.TMA_CommodityCtg.fld_Description, Document.HKLCommodityCtgTelai);
			ctrl_Description2.AddChangedProperty("Caption");
			ctrl_Description2.Border = true;
			ctrl_Description2.AddChangedProperty("Border");
			ctrl_Description2.Size = new System.Drawing.Size(240, 23);
			ctrl_Description2.AddChangedProperty("Size");
			MLabelProperties ctrl_Description2_MLabelProperties = (MLabelProperties)ctrl_Description2.Extensions["MLabelProperties"];
			ctrl_Description2_MLabelProperties.Sunken = true;
			ctrl_Description2_MLabelProperties.AddChangedProperty("Sunken");
			this.Add(ctrl_Description2, true);
			ctrl_Description3 = new Microarea.Framework.TBApplicationWrapper.MParsedStatic(this, "Description3", "StringStatic", new System.Drawing.Point(375, 187), false);
			ctrl_Description3.DataBinding = new FieldDataBinding(Document.HKLCommodityCtgPannelli.TMA_CommodityCtg.fld_Description, Document.HKLCommodityCtgPannelli);
			ctrl_Description3.AddChangedProperty("Caption");
			ctrl_Description3.Border = true;
			ctrl_Description3.AddChangedProperty("Border");
			ctrl_Description3.Size = new System.Drawing.Size(240, 23);
			ctrl_Description3.AddChangedProperty("Size");
			MLabelProperties ctrl_Description3_MLabelProperties = (MLabelProperties)ctrl_Description3.Extensions["MLabelProperties"];
			ctrl_Description3_MLabelProperties.Sunken = true;
			ctrl_Description3_MLabelProperties.AddChangedProperty("Sunken");
			this.Add(ctrl_Description3, true);
			ctrl_Description4 = new Microarea.Framework.TBApplicationWrapper.MParsedStatic(this, "Description4", "StringStatic", new System.Drawing.Point(376, 233), false);
			ctrl_Description4.DataBinding = new FieldDataBinding(Document.HKLCommodityCtgAccessori.TMA_CommodityCtg.fld_Description, Document.HKLCommodityCtgAccessori);
			ctrl_Description4.AddChangedProperty("Caption");
			ctrl_Description4.Border = true;
			ctrl_Description4.AddChangedProperty("Border");
			ctrl_Description4.Size = new System.Drawing.Size(240, 23);
			ctrl_Description4.AddChangedProperty("Size");
			MLabelProperties ctrl_Description4_MLabelProperties = (MLabelProperties)ctrl_Description4.Extensions["MLabelProperties"];
			ctrl_Description4_MLabelProperties.Sunken = true;
			ctrl_Description4_MLabelProperties.AddChangedProperty("Sunken");
			this.Add(ctrl_Description4, true);
			ctrl_Description5 = new Microarea.Framework.TBApplicationWrapper.MParsedStatic(this, "Description5", "StringStatic", new System.Drawing.Point(375, 285), false);
			ctrl_Description5.DataBinding = new FieldDataBinding(Document.HKLCommodityCtgPannelliLav.TMA_CommodityCtg.fld_Description, Document.HKLCommodityCtgPannelliLav);
			ctrl_Description5.AddChangedProperty("Caption");
			ctrl_Description5.Border = true;
			ctrl_Description5.AddChangedProperty("Border");
			ctrl_Description5.Size = new System.Drawing.Size(239, 23);
			ctrl_Description5.AddChangedProperty("Size");
			MLabelProperties ctrl_Description5_MLabelProperties = (MLabelProperties)ctrl_Description5.Extensions["MLabelProperties"];
			ctrl_Description5_MLabelProperties.Sunken = true;
			ctrl_Description5_MLabelProperties.AddChangedProperty("Sunken");
			this.Add(ctrl_Description5, true);
			ctrl_Description6 = new Microarea.Framework.TBApplicationWrapper.MParsedStatic(this, "Description6", "StringStatic", new System.Drawing.Point(374, 335), false);
			ctrl_Description6.DataBinding = new FieldDataBinding(Document.HKLCommodityCtgTelaiLav.TMA_CommodityCtg.fld_Description, Document.HKLCommodityCtgTelaiLav);
			ctrl_Description6.AddChangedProperty("Caption");
			ctrl_Description6.Border = true;
			ctrl_Description6.AddChangedProperty("Border");
			ctrl_Description6.Size = new System.Drawing.Size(240, 23);
			ctrl_Description6.AddChangedProperty("Size");
			MLabelProperties ctrl_Description6_MLabelProperties = (MLabelProperties)ctrl_Description6.Extensions["MLabelProperties"];
			ctrl_Description6_MLabelProperties.Sunken = true;
			ctrl_Description6_MLabelProperties.AddChangedProperty("Sunken");
			this.Add(ctrl_Description6, true);
			ctrl_Description7 = new Microarea.Framework.TBApplicationWrapper.MParsedStatic(this, "Description7", "StringStatic", new System.Drawing.Point(375, 378), false);
			ctrl_Description7.DataBinding = new FieldDataBinding(Document.HKLCommodityCtgCoprifiliLav.TMA_CommodityCtg.fld_Description, Document.HKLCommodityCtgCoprifiliLav);
			ctrl_Description7.AddChangedProperty("Caption");
			ctrl_Description7.Border = true;
			ctrl_Description7.AddChangedProperty("Border");
			ctrl_Description7.Size = new System.Drawing.Size(239, 23);
			ctrl_Description7.AddChangedProperty("Size");
			MLabelProperties ctrl_Description7_MLabelProperties = (MLabelProperties)ctrl_Description7.Extensions["MLabelProperties"];
			ctrl_Description7_MLabelProperties.Sunken = true;
			ctrl_Description7_MLabelProperties.AddChangedProperty("Sunken");
			this.Add(ctrl_Description7, true);
			ctrl_Description8 = new Microarea.Framework.TBApplicationWrapper.MParsedStatic(this, "Description8", "StringStatic", new System.Drawing.Point(374, 428), false);
			ctrl_Description8.DataBinding = new FieldDataBinding(Document.HKLCommodityCtgCfAl.TMA_CommodityCtg.fld_Description, Document.HKLCommodityCtgCfAl);
			ctrl_Description8.AddChangedProperty("DataBinding");
			ctrl_Description8.AddChangedProperty("Caption");
			ctrl_Description8.Border = true;
			ctrl_Description8.AddChangedProperty("Border");
			ctrl_Description8.Size = new System.Drawing.Size(240, 23);
			ctrl_Description8.AddChangedProperty("Size");
			MLabelProperties ctrl_Description8_MLabelProperties = (MLabelProperties)ctrl_Description8.Extensions["MLabelProperties"];
			ctrl_Description8_MLabelProperties.Sunken = true;
			ctrl_Description8_MLabelProperties.AddChangedProperty("Sunken");
			this.Add(ctrl_Description8, true);
			ctrl_Description9 = new Microarea.Framework.TBApplicationWrapper.MParsedStatic(this, "Description9", "StringStatic", new System.Drawing.Point(376, 474), false);
			ctrl_Description9.DataBinding = new FieldDataBinding(Document.HKLCommodityCtgFerramenta.TMA_CommodityCtg.fld_Description, Document.HKLCommodityCtgFerramenta);
			ctrl_Description9.AddChangedProperty("DataBinding");
			ctrl_Description9.AddChangedProperty("Caption");
			ctrl_Description9.Border = true;
			ctrl_Description9.AddChangedProperty("Border");
			ctrl_Description9.Size = new System.Drawing.Size(238, 23);
			ctrl_Description9.AddChangedProperty("Size");
			MLabelProperties ctrl_Description9_MLabelProperties = (MLabelProperties)ctrl_Description9.Extensions["MLabelProperties"];
			ctrl_Description9_MLabelProperties.Sunken = true;
			ctrl_Description9_MLabelProperties.AddChangedProperty("Sunken");
			this.Add(ctrl_Description9, true);
			ctrl_IDC_STATIC_AREA = new Microarea.Framework.TBApplicationWrapper.GenericGroupBox(this, "IDC_STATIC_AREA", "Button", new System.Drawing.Point(7, 24), new System.Drawing.Point(0, 0), false);
			ctrl_IDC_STATIC_AREA.Size = new System.Drawing.Size(175, 343);
			ctrl_IDC_STATIC_AREA.AddChangedProperty("Size");
			this.Add(ctrl_IDC_STATIC_AREA, true);
			ctrl_CatMercImbotti = new Microarea.Framework.TBApplicationWrapper.MParsedEdit(this, "CatMercImbotti", "StringEdit", new System.Drawing.Point(184, 53), false);
			ctrl_CatMercImbotti.DataBinding = new FieldDataBinding(Document.DBTDOORSParams.TTAG_DOORS_Params.fld_CatMercImbotti, Document.DBTDOORSParams);
			ctrl_CatMercImbotti.AddChangedProperty("DataBinding");
			ctrl_CatMercImbotti.AddChangedProperty("Caption");
			ctrl_CatMercImbotti.HotLink = Document.HKLCommodityCtg;
			ctrl_CatMercImbotti.AddChangedProperty("HotLink");
			ctrl_CatMercImbotti.Size = new System.Drawing.Size(156, 22);
			ctrl_CatMercImbotti.AddChangedProperty("Size");
			this.Add(ctrl_CatMercImbotti, true);
			ctrl_CatMercPorte = new Microarea.Framework.TBApplicationWrapper.MParsedEdit(this, "CatMercPorte", "StringEdit", new System.Drawing.Point(184, 99), false);
			ctrl_CatMercPorte.DataBinding = new FieldDataBinding(Document.DBTDOORSParams.TTAG_DOORS_Params.fld_CatMercPorte, Document.DBTDOORSParams);
			ctrl_CatMercPorte.AddChangedProperty("DataBinding");
			ctrl_CatMercPorte.AddChangedProperty("Caption");
			ctrl_CatMercPorte.HotLink = Document.HKLCommodityCtgPorte;
			ctrl_CatMercPorte.AddChangedProperty("HotLink");
			ctrl_CatMercPorte.Size = new System.Drawing.Size(156, 22);
			ctrl_CatMercPorte.AddChangedProperty("Size");
			this.Add(ctrl_CatMercPorte, true);
			ctrl_CatMercTelai = new Microarea.Framework.TBApplicationWrapper.MParsedEdit(this, "CatMercTelai", "StringEdit", new System.Drawing.Point(184, 143), false);
			ctrl_CatMercTelai.DataBinding = new FieldDataBinding(Document.DBTDOORSParams.TTAG_DOORS_Params.fld_CatMercTelai, Document.DBTDOORSParams);
			ctrl_CatMercTelai.AddChangedProperty("DataBinding");
			ctrl_CatMercTelai.AddChangedProperty("Caption");
			ctrl_CatMercTelai.HotLink = Document.HKLCommodityCtgTelai;
			ctrl_CatMercTelai.AddChangedProperty("HotLink");
			ctrl_CatMercTelai.Size = new System.Drawing.Size(156, 22);
			ctrl_CatMercTelai.AddChangedProperty("Size");
			this.Add(ctrl_CatMercTelai, true);
			ctrl_CatMercPannelli = new Microarea.Framework.TBApplicationWrapper.MParsedEdit(this, "CatMercPannelli", "StringEdit", new System.Drawing.Point(184, 188), false);
			ctrl_CatMercPannelli.DataBinding = new FieldDataBinding(Document.DBTDOORSParams.TTAG_DOORS_Params.fld_CatMercPannelli, Document.DBTDOORSParams);
			ctrl_CatMercPannelli.AddChangedProperty("Caption");
			ctrl_CatMercPannelli.HotLink = Document.HKLCommodityCtgPannelli;
			ctrl_CatMercPannelli.AddChangedProperty("HotLink");
			ctrl_CatMercPannelli.Size = new System.Drawing.Size(156, 22);
			ctrl_CatMercPannelli.AddChangedProperty("Size");
			this.Add(ctrl_CatMercPannelli, true);
			ctrl_CatMercAccessori = new Microarea.Framework.TBApplicationWrapper.MParsedEdit(this, "CatMercAccessori", "StringEdit", new System.Drawing.Point(184, 234), false);
			ctrl_CatMercAccessori.DataBinding = new FieldDataBinding(Document.DBTDOORSParams.TTAG_DOORS_Params.fld_CatMercAccessori, Document.DBTDOORSParams);
			ctrl_CatMercAccessori.AddChangedProperty("Caption");
			ctrl_CatMercAccessori.HotLink = Document.HKLCommodityCtgAccessori;
			ctrl_CatMercAccessori.AddChangedProperty("HotLink");
			ctrl_CatMercAccessori.Size = new System.Drawing.Size(156, 22);
			ctrl_CatMercAccessori.AddChangedProperty("Size");
			this.Add(ctrl_CatMercAccessori, true);
			ctrl_CatMercPanneliLav = new Microarea.Framework.TBApplicationWrapper.MParsedEdit(this, "CatMercPanneliLav", "StringEdit", new System.Drawing.Point(184, 285), false);
			ctrl_CatMercPanneliLav.DataBinding = new FieldDataBinding(Document.DBTDOORSParams.TTAG_DOORS_Params.fld_CatMercPanneliLav, Document.DBTDOORSParams);
			ctrl_CatMercPanneliLav.AddChangedProperty("DataBinding");
			ctrl_CatMercPanneliLav.AddChangedProperty("Caption");
			ctrl_CatMercPanneliLav.HotLink = Document.HKLCommodityCtgPannelliLav;
			ctrl_CatMercPanneliLav.AddChangedProperty("HotLink");
			ctrl_CatMercPanneliLav.Size = new System.Drawing.Size(156, 23);
			ctrl_CatMercPanneliLav.AddChangedProperty("Size");
			this.Add(ctrl_CatMercPanneliLav, true);
			ctrl_CatMercTelaiLav = new Microarea.Framework.TBApplicationWrapper.MParsedEdit(this, "CatMercTelaiLav", "StringEdit", new System.Drawing.Point(184, 335), false);
			ctrl_CatMercTelaiLav.DataBinding = new FieldDataBinding(Document.DBTDOORSParams.TTAG_DOORS_Params.fld_CatMercTelaiLav, Document.DBTDOORSParams);
			ctrl_CatMercTelaiLav.AddChangedProperty("DataBinding");
			ctrl_CatMercTelaiLav.AddChangedProperty("Caption");
			ctrl_CatMercTelaiLav.HotLink = Document.HKLCommodityCtgTelaiLav;
			ctrl_CatMercTelaiLav.AddChangedProperty("HotLink");
			ctrl_CatMercTelaiLav.Size = new System.Drawing.Size(156, 23);
			ctrl_CatMercTelaiLav.AddChangedProperty("Size");
			this.Add(ctrl_CatMercTelaiLav, true);
			ctrl_CatMercCoprifiliLav = new Microarea.Framework.TBApplicationWrapper.MParsedEdit(this, "CatMercCoprifiliLav", "StringEdit", new System.Drawing.Point(184, 378), false);
			ctrl_CatMercCoprifiliLav.DataBinding = new FieldDataBinding(Document.DBTDOORSParams.TTAG_DOORS_Params.fld_CatMercCoprifiliLav, Document.DBTDOORSParams);
			ctrl_CatMercCoprifiliLav.AddChangedProperty("DataBinding");
			ctrl_CatMercCoprifiliLav.AddChangedProperty("Caption");
			ctrl_CatMercCoprifiliLav.HotLink = Document.HKLCommodityCtgCoprifiliLav;
			ctrl_CatMercCoprifiliLav.AddChangedProperty("HotLink");
			ctrl_CatMercCoprifiliLav.Size = new System.Drawing.Size(156, 23);
			ctrl_CatMercCoprifiliLav.AddChangedProperty("Size");
			this.Add(ctrl_CatMercCoprifiliLav, true);
			ctrl_CatMercCfAlettaLunga = new Microarea.Framework.TBApplicationWrapper.MParsedEdit(this, "CatMercCfAlettaLunga", "StringEdit", new System.Drawing.Point(184, 428), false);
			ctrl_CatMercCfAlettaLunga.DataBinding = new FieldDataBinding(Document.DBTDOORSParams.TTAG_DOORS_Params.fld_CatMercCfAlettaLunga, Document.DBTDOORSParams);
			ctrl_CatMercCfAlettaLunga.AddChangedProperty("Caption");
			ctrl_CatMercCfAlettaLunga.HotLink = Document.HKLCommodityCtgCfAl;
			ctrl_CatMercCfAlettaLunga.AddChangedProperty("HotLink");
			ctrl_CatMercCfAlettaLunga.Size = new System.Drawing.Size(156, 23);
			ctrl_CatMercCfAlettaLunga.AddChangedProperty("Size");
			this.Add(ctrl_CatMercCfAlettaLunga, true);
			ctrl_CatMercFerramenta = new Microarea.Framework.TBApplicationWrapper.MParsedEdit(this, "CatMercFerramenta", "StringEdit", new System.Drawing.Point(184, 474), false);
			ctrl_CatMercFerramenta.DataBinding = new FieldDataBinding(Document.DBTDOORSParams.TTAG_DOORS_Params.fld_CatMercFerramenta, Document.DBTDOORSParams);
			ctrl_CatMercFerramenta.AddChangedProperty("Caption");
			ctrl_CatMercFerramenta.HotLink = Document.HKLCommodityCtgFerramenta;
			ctrl_CatMercFerramenta.AddChangedProperty("HotLink");
			ctrl_CatMercFerramenta.Size = new System.Drawing.Size(156, 23);
			ctrl_CatMercFerramenta.AddChangedProperty("Size");
			this.Add(ctrl_CatMercFerramenta, true);
			ctrl_CatMercVetri = new Microarea.Framework.TBApplicationWrapper.MParsedEdit(this, "CatMercVetri", "StringEdit", new System.Drawing.Point(184, 519), false);
			ctrl_CatMercVetri.DataBinding = new FieldDataBinding(Document.DBTDOORSParams.TTAG_DOORS_Params.fld_CatMercVetri, Document.DBTDOORSParams);
			ctrl_CatMercVetri.AddChangedProperty("Caption");
			ctrl_CatMercVetri.HotLink = Document.HKLCommodityCtgVetri;
			ctrl_CatMercVetri.AddChangedProperty("HotLink");
			ctrl_CatMercVetri.Size = new System.Drawing.Size(156, 23);
			ctrl_CatMercVetri.AddChangedProperty("Size");
			this.Add(ctrl_CatMercVetri, true);
		}

		public override void ApplyResources()
		{
			Microarea.EasyBuilder.CustomizationComponentResourceManager resources = Strings.ResourceManager;
			resources.ApplyResources(ctrl_Description, "ctrl_Description");
			resources.ApplyResources(ctrl_Description1, "ctrl_Description1");
			resources.ApplyResources(ctrl_Description10, "ctrl_Description10");
			resources.ApplyResources(ctrl_Description2, "ctrl_Description2");
			resources.ApplyResources(ctrl_Description3, "ctrl_Description3");
			resources.ApplyResources(ctrl_Description4, "ctrl_Description4");
			resources.ApplyResources(ctrl_Description5, "ctrl_Description5");
			resources.ApplyResources(ctrl_Description6, "ctrl_Description6");
			resources.ApplyResources(ctrl_Description7, "ctrl_Description7");
			resources.ApplyResources(ctrl_Description8, "ctrl_Description8");
			resources.ApplyResources(ctrl_Description9, "ctrl_Description9");
			resources.ApplyResources(ctrl_IDC_STATIC_AREA, "ctrl_IDC_STATIC_AREA");
			resources.ApplyResources(ctrl_CatMercImbotti, "ctrl_CatMercImbotti");
			resources.ApplyResources(ctrl_CatMercPorte, "ctrl_CatMercPorte");
			resources.ApplyResources(ctrl_CatMercTelai, "ctrl_CatMercTelai");
			resources.ApplyResources(ctrl_CatMercPannelli, "ctrl_CatMercPannelli");
			resources.ApplyResources(ctrl_CatMercAccessori, "ctrl_CatMercAccessori");
			resources.ApplyResources(ctrl_CatMercPanneliLav, "ctrl_CatMercPanneliLav");
			resources.ApplyResources(ctrl_CatMercTelaiLav, "ctrl_CatMercTelaiLav");
			resources.ApplyResources(ctrl_CatMercCoprifiliLav, "ctrl_CatMercCoprifiliLav");
			resources.ApplyResources(ctrl_CatMercCfAlettaLunga, "ctrl_CatMercCfAlettaLunga");
			resources.ApplyResources(ctrl_CatMercFerramenta, "ctrl_CatMercFerramenta");
			resources.ApplyResources(ctrl_CatMercVetri, "ctrl_CatMercVetri");
		}

		public override void ClearComponents()
		{
			base.ClearComponents();
			ctrl_Description = null;
			ctrl_Description1 = null;
			ctrl_Description10 = null;
			ctrl_Description2 = null;
			ctrl_Description3 = null;
			ctrl_Description4 = null;
			ctrl_Description5 = null;
			ctrl_Description6 = null;
			ctrl_Description7 = null;
			ctrl_Description8 = null;
			ctrl_Description9 = null;
			ctrl_IDC_STATIC_AREA = null;
			ctrl_CatMercImbotti = null;
			ctrl_CatMercPorte = null;
			ctrl_CatMercTelai = null;
			ctrl_CatMercPannelli = null;
			ctrl_CatMercAccessori = null;
			ctrl_CatMercPanneliLav = null;
			ctrl_CatMercTelaiLav = null;
			ctrl_CatMercCoprifiliLav = null;
			ctrl_CatMercCfAlettaLunga = null;
			ctrl_CatMercFerramenta = null;
			ctrl_CatMercVetri = null;
		}
	}
}
