ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "LARGHEZZA" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "LARGHEZZA" = 0 WHERE "LARGHEZZA" IS NULL
GO


ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "ALTEZZA" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "ALTEZZA" = 0 WHERE "ALTEZZA" IS NULL
GO


ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "SPESSOREMURO" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "SPESSOREMURO" = 0 WHERE "SPESSOREMURO" IS NULL
GO


ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "SPESSORETELAIO" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "SPESSORETELAIO" = 0 WHERE "SPESSORETELAIO" IS NULL
GO


ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "NOTECONFTEXT" clob DEFAULT ('')
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "NOTECONFTEXT" = '' WHERE "NOTECONFTEXT" IS NULL
GO


