ALTER TABLE "MA_ITEMS"
ADD "DOORSAPERTURA" VARCHAR2 (12) DEFAULT ('')
GO


UPDATE "MA_ITEMS" SET "DOORSAPERTURA" = '' WHERE "DOORSAPERTURA" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSNOTE" VARCHAR2 (50) DEFAULT ('')
GO


UPDATE "MA_ITEMS" SET "DOORSNOTE" = '' WHERE "DOORSNOTE" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSLARGHEZZA" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSLARGHEZZA" = 0 WHERE "DOORSLARGHEZZA" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSALTEZZA" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSALTEZZA" = 0 WHERE "DOORSALTEZZA" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSFINITURA" VARCHAR2 (8) DEFAULT ('')
GO


UPDATE "MA_ITEMS" SET "DOORSFINITURA" = '' WHERE "DOORSFINITURA" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSBATTUTA" VARCHAR2 (8) DEFAULT ('')
GO


UPDATE "MA_ITEMS" SET "DOORSBATTUTA" = '' WHERE "DOORSBATTUTA" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSTIPOTELAIO" VARCHAR2 (8) DEFAULT ('')
GO


UPDATE "MA_ITEMS" SET "DOORSTIPOTELAIO" = '' WHERE "DOORSTIPOTELAIO" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSSPESSORE" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSSPESSORE" = 0 WHERE "DOORSSPESSORE" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSLARGHEZZAINTBATT" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSLARGHEZZAINTBATT" = 0 WHERE "DOORSLARGHEZZAINTBATT" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSALTEZZAINTBATT" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSALTEZZAINTBATT" = 0 WHERE "DOORSALTEZZAINTBATT" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSARIAL" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSARIAL" = 0 WHERE "DOORSARIAL" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSARIAH" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSARIAH" = 0 WHERE "DOORSARIAH" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSSPPROFINTTELAIO" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSSPPROFINTTELAIO" = 0 WHERE "DOORSSPPROFINTTELAIO" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSSPPROFESTTELAIO" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSSPPROFESTTELAIO" = 0 WHERE "DOORSSPPROFESTTELAIO" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "HVETRO" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "HVETRO" = 0 WHERE "HVETRO" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "LVETRO" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "LVETRO" = 0 WHERE "LVETRO" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSLNOMINALE" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSLNOMINALE" = 0 WHERE "DOORSLNOMINALE" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSHNOMINALE" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSHNOMINALE" = 0 WHERE "DOORSHNOMINALE" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSPNOMINALE" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSPNOMINALE" = 0 WHERE "DOORSPNOMINALE" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSCOEFFL" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSCOEFFL" = 0 WHERE "DOORSCOEFFL" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSCOEFFH" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSCOEFFH" = 0 WHERE "DOORSCOEFFH" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSCOEFFP" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSCOEFFP" = 0 WHERE "DOORSCOEFFP" IS NULL
GO


