CREATE TABLE "TAG_DOORS_PARAMS" (
    "TBGUID" CHAR(38) DEFAULT ('00000000-0000-0000-0000-000000000000'),
    "ID" NUMBER (6) NOT NULL,
    "SERVER" VARCHAR2 (150) DEFAULT (''),
    "INSTALLAZIONE" VARCHAR2 (50) DEFAULT (''),
    "PORTA" NUMBER (6) DEFAULT (0),
    "COMPANY" VARCHAR2 (50) DEFAULT (''),
    "USER" VARCHAR2 (50) DEFAULT (''),
    "PASSWORD" VARCHAR2 (50) DEFAULT (''),
    "UTENTEMAGO" VARCHAR2 (50) DEFAULT (''),
    "PROGCONF" NUMBER (10) DEFAULT (0),
    "CATMERCPORTE" VARCHAR2 (8) DEFAULT (''),
    "CATMERCTELAI" VARCHAR2 (8) DEFAULT (''),
    "CATMERCIMBOTTI" VARCHAR2 (8) DEFAULT (''),
    "CATMERCPANNELLI" VARCHAR2 (8) DEFAULT (''),
    "CATMERCACCESSORI" VARCHAR2 (8) DEFAULT (''),
    "CATMERCPANNELILAV" VARCHAR2 (8) DEFAULT (''),
    "OPERAZIONEFUORIMISURA" VARCHAR2 (21) DEFAULT (''),
    "OPFUORIMISURAPRIMADI" VARCHAR2 (21) DEFAULT (''),
    "OPFUORIMISURAULTIMA" CHAR (1) DEFAULT ('0'),
    "OPFUORIMISURADOPODI" VARCHAR2 (21) DEFAULT (''),
    "CATMERCTELAILAV" VARCHAR2 (8) DEFAULT (''),
    "CATMERCCOPRIFILILAV" VARCHAR2 (8) DEFAULT (''),
    "CATMERCCFALETTALUNGA" VARCHAR2 (8) DEFAULT (''),
    "CATMERCFERRAMENTA" VARCHAR2 (8) DEFAULT (''),
    "CATMERCVETRI" VARCHAR2 (8) DEFAULT (''),
    CONSTRAINT "PK_TAG_DOORS_PARAMS" PRIMARY KEY
    (
        "ID"
    )
)
GO
