CREATE TABLE "TAG_DOORS_POLTELAIODETAIL" (
    "CODICE" VARCHAR2 (21) NOT NULL,
    "RIGA" NUMBER (6) NOT NULL,
    "SPDA" FLOAT (126) DEFAULT (0),
    "SPA" FLOAT (126) DEFAULT (0),
    "LCF" FLOAT (126) DEFAULT (0),
    "QTACF" FLOAT (126) DEFAULT (0),
    "LCFAL" FLOAT (126) DEFAULT (0),
    "QTACFAL" FLOAT (126) DEFAULT (0),
    "IMBOTTO" CHAR (1) DEFAULT ('0'),
    "QTAIMB" FLOAT (126) DEFAULT (0),
    "LCF1" FLOAT (126) DEFAULT (0),
    "QYACF1" FLOAT (126) DEFAULT (0),
    "LTELAIO" FLOAT (126) DEFAULT (0),
    CONSTRAINT "PK_TAG_DOORS_POLTELAIODETAIL" PRIMARY KEY
    (
        "CODICE",
        "RIGA"
    )
)
GO
