CREATE TABLE "TAG_DOORS_MAGGIORAZIONIDETAIL" (
    "CTGPROD" VARCHAR2 (8) NOT NULL,
    "SUBCTGPROD" VARCHAR2 (8) NOT NULL,
    "CUSTOMER" VARCHAR2 (12) NOT NULL,
    "RIGA" NUMBER (6) NOT NULL,
    "ITEM" VARCHAR2 (21) DEFAULT (''),
    "DESCRIZIONE" VARCHAR2 (64) DEFAULT (''),
    "IMPORTO" FLOAT (126) DEFAULT (0),
    "TIPOMAGGIORAZIONE" NUMBER (10) DEFAULT (996409344),
    "DIMENSIONE" NUMBER (10) DEFAULT (1543569408),
    "DADIM" FLOAT (126) DEFAULT (0),
    "ADIM" FLOAT (126) DEFAULT (0),
    "APERTURA" VARCHAR2 (12) DEFAULT (''),
    "OLTRESTANDARD" FLOAT (126) DEFAULT (0),
    CONSTRAINT "PK_TAG_DOORS_MAGGIORAZIONIDETAIL" PRIMARY KEY
    (
        "CTGPROD",
        "SUBCTGPROD",
        "CUSTOMER",
        "RIGA"
    )
)
GO
