CREATE TABLE "TAG_DOORS_CONFIGMAGG" (
    "IDGUID" VARCHAR2 (50) NOT NULL,
    "LINE" NUMBER (6) NOT NULL,
    "SUBCTGPROD" VARCHAR2 (8) DEFAULT (''),
    "RIGAMAGG" NUMBER (6) DEFAULT (0),
    "CUSTOMER" VARCHAR2 (12) DEFAULT (''),
    "CTGPROD" VARCHAR2 (8) DEFAULT (''),
    "TIPOMAGGIORAZIONE" NUMBER (10) DEFAULT (996409344),
    "OLTRESTANDARD" FLOAT (126) DEFAULT (0),
    "ITEM" VARCHAR2 (21) DEFAULT (''),
    "IMPORTO" FLOAT (126) DEFAULT (0),
    "DIMENSIONE" NUMBER (10) DEFAULT (1543569408),
    "DESCRIZIONE" VARCHAR2 (64) DEFAULT (''),
    "DADIM" FLOAT (126) DEFAULT (0),
    "ADIM" FLOAT (126) DEFAULT (0),
    "APERTURA" VARCHAR2 (12) DEFAULT (''),
    CONSTRAINT "PK_TAG_DOORS_CONFIGMAGG" PRIMARY KEY
    (
        "IDGUID",
        "LINE"
    )
)
GO
