ALTER TABLE "TAG_DOORS_CONFIGURAZIONIDETAIL"
ADD "NOTEOPERAZIONE" VARCHAR2 (254) DEFAULT ('')
GO


UPDATE "TAG_DOORS_CONFIGURAZIONIDETAIL" SET "NOTEOPERAZIONE" = '' WHERE "NOTEOPERAZIONE" IS NULL
GO


ALTER TABLE "TAG_DOORS_CONFIGURAZIONIDETAIL"
ADD "NOTECOMPONENTE" VARCHAR2 (64) DEFAULT ('')
GO


UPDATE "TAG_DOORS_CONFIGURAZIONIDETAIL" SET "NOTECOMPONENTE" = '' WHERE "NOTECOMPONENTE" IS NULL
GO


