CREATE TABLE "TAG_DOORS_CONFIGURAZIONIDETAIL" (
    "IDGUID" VARCHAR2 (50) NOT NULL,
    "LINE" NUMBER (6) NOT NULL,
    "COMPONENT" VARCHAR2 (21) DEFAULT (''),
    "COMPONENTDESCRIPTION" VARCHAR2 (128) DEFAULT (''),
    "ISRTGSTEP" CHAR (1) DEFAULT ('0'),
    "QTY" FLOAT (126) DEFAULT (0),
    "BOMLEVEL" NUMBER (6) DEFAULT (0),
    "PARENTBOM" VARCHAR2 (21) DEFAULT (''),
    "BOM" VARCHAR2 (21) DEFAULT (''),
    "BREAKINGBOM" VARCHAR2 (21) DEFAULT (''),
    "BREAKINGITEM" VARCHAR2 (21) DEFAULT (''),
    "ISABOM" CHAR (1) DEFAULT ('0'),
    "NOTE" VARCHAR2 (250) DEFAULT (''),
    "EXPLOSIONLINE" NUMBER (6) DEFAULT (0),
    "NOTEOPERAZIONE" VARCHAR2 (254) DEFAULT (''),
    "NOTECOMPONENTE" VARCHAR2 (64) DEFAULT (''),
    "FASE" NUMBER (6) DEFAULT (0),
    CONSTRAINT "PK_TAG_DOORS_CONFIGURAZIONIDETAIL" PRIMARY KEY
    (
        "IDGUID",
        "LINE"
    )
)
GO
