CREATE TABLE "TAG_DOORS_CONFIGURAZIONI" (
    "TBGUID" CHAR(38) DEFAULT ('00000000-0000-0000-0000-000000000000'),
    "IDGUID" VARCHAR2 (50) NOT NULL,
    "SALEORDID" NUMBER (10) DEFAULT (0),
    "POSITIONSALEORD" NUMBER (6) DEFAULT (0),
    "LINESALEORD" NUMBER (6) DEFAULT (0),
    "LARGHEZZA" FLOAT (126) DEFAULT (0),
    "ALTEZZA" FLOAT (126) DEFAULT (0),
    "SPESSOREMURO" FLOAT (126) DEFAULT (0),
    "SPESSORETELAIO" FLOAT (126) DEFAULT (0),
    "NOTECONFTEXT" clob DEFAULT (''),
    "ROOTITEM" VARCHAR2 (21) DEFAULT (''),
    "VARIANTEROOT" VARCHAR2 (21) DEFAULT (''),
    "VARIANTESTANDARD" CHAR (1) DEFAULT ('0'),
    "DESCROOTVAR" VARCHAR2 (250) DEFAULT (''),
    "LINTBATTUTA" FLOAT (126) DEFAULT (0),
    "HINTBATTUTA" FLOAT (126) DEFAULT (0),
    "ARIAH" FLOAT (126) DEFAULT (0),
    "ARIAL" FLOAT (126) DEFAULT (0),
    CONSTRAINT "PK_TAG_DOORS_CONFIGURAZIONI" PRIMARY KEY
    (
        "IDGUID"
    )
)
GO
