ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "LINTBATTUTA" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "LINTBATTUTA" = 0 WHERE "LINTBATTUTA" IS NULL
GO


ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "HINTBATTUTA" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "HINTBATTUTA" = 0 WHERE "HINTBATTUTA" IS NULL
GO


ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "ARIAH" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "ARIAH" = 0 WHERE "ARIAH" IS NULL
GO


ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "ARIAL" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "ARIAL" = 0 WHERE "ARIAL" IS NULL
GO


