CREATE TABLE "TAG_DOORS_PARAMSIN" (
    "IDPARAM" NUMBER (6) NOT NULL,
    "CATPROD" VARCHAR2 (8) NOT NULL,
    CONSTRAINT "PK_TAG_DOORS_PARAMSIN" PRIMARY KEY
    (
        "IDPARAM",
        "CATPROD"
    )
)
GO
