ALTER TABLE "TAG_DOORS_TABELLAPANNELLIR"
ADD "BATTUTACOMPONENTE" VARCHAR2 (8) DEFAULT ('')
GO


UPDATE "TAG_DOORS_TABELLAPANNELLIR" SET "BATTUTACOMPONENTE" = '' WHERE "BATTUTACOMPONENTE" IS NULL
GO


