CREATE TABLE "TAG_DOORS_CONFIGVETRI" (
    "IDGUID" VARCHAR2 (50) NOT NULL,
    "LINE" NUMBER (6) NOT NULL,
    "ITEM" VARCHAR2 (21) DEFAULT (''),
    "DESCRIPTION" VARCHAR2 (150) DEFAULT (''),
    "QTY" FLOAT (126) DEFAULT (0),
    CONSTRAINT "PK_TAG_DOORS_CONFIGVETRI" PRIMARY KEY
    (
        "IDGUID",
        "LINE"
    )
)
GO
