ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "VARIANTEROOT" VARCHAR2 (21) DEFAULT ('')
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "VARIANTEROOT" = '' WHERE "VARIANTEROOT" IS NULL
GO


ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "VARIANTESTANDARD" CHAR (1) DEFAULT ('0')
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "VARIANTESTANDARD" = '0' WHERE "VARIANTESTANDARD" IS NULL
GO


ALTER TABLE "TAG_DOORS_CONFIGURAZIONI"
ADD "DESCROOTVAR" VARCHAR2 (250) DEFAULT ('')
GO


UPDATE "TAG_DOORS_CONFIGURAZIONI" SET "DESCROOTVAR" = '' WHERE "DESCROOTVAR" IS NULL
GO


