ALTER TABLE "TAG_DOORS_PARAMS"
ADD "OPFUORIMISURAPRIMADI" VARCHAR2 (21) DEFAULT ('')
GO


UPDATE "TAG_DOORS_PARAMS" SET "OPFUORIMISURAPRIMADI" = '' WHERE "OPFUORIMISURAPRIMADI" IS NULL
GO


ALTER TABLE "TAG_DOORS_PARAMS"
ADD "OPFUORIMISURAULTIMA" CHAR (1) DEFAULT ('0')
GO


UPDATE "TAG_DOORS_PARAMS" SET "OPFUORIMISURAULTIMA" = '0' WHERE "OPFUORIMISURAULTIMA" IS NULL
GO


