ALTER TABLE "MA_ITEMS"
ADD "DOORSLNOMINALE" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSLNOMINALE" = 0 WHERE "DOORSLNOMINALE" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSHNOMINALE" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSHNOMINALE" = 0 WHERE "DOORSHNOMINALE" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSPNOMINALE" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSPNOMINALE" = 0 WHERE "DOORSPNOMINALE" IS NULL
GO


