ALTER TABLE "TAG_DOORS_MAGGIORAZIONI"
ADD "SCONTOMAGG1" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_MAGGIORAZIONI" SET "SCONTOMAGG1" = 0 WHERE "SCONTOMAGG1" IS NULL
GO


ALTER TABLE "TAG_DOORS_MAGGIORAZIONI"
ADD "SCONTOMAGG2" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_MAGGIORAZIONI" SET "SCONTOMAGG2" = 0 WHERE "SCONTOMAGG2" IS NULL
GO


ALTER TABLE "TAG_DOORS_MAGGIORAZIONI"
ADD "SCONTOMAGG3" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_MAGGIORAZIONI" SET "SCONTOMAGG3" = 0 WHERE "SCONTOMAGG3" IS NULL
GO


