ALTER TABLE "TAG_DOORS_MAGGIORAZIONIDETAIL"
ADD "DIMENSIONE" NUMBER (10) DEFAULT (1543569408)
GO


UPDATE "TAG_DOORS_MAGGIORAZIONIDETAIL" SET "DIMENSIONE" = 1543569408 WHERE "DIMENSIONE" IS NULL
GO


ALTER TABLE "TAG_DOORS_MAGGIORAZIONIDETAIL"
ADD "DADIM" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_MAGGIORAZIONIDETAIL" SET "DADIM" = 0 WHERE "DADIM" IS NULL
GO


ALTER TABLE "TAG_DOORS_MAGGIORAZIONIDETAIL"
ADD "ADIM" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_MAGGIORAZIONIDETAIL" SET "ADIM" = 0 WHERE "ADIM" IS NULL
GO


ALTER TABLE "TAG_DOORS_MAGGIORAZIONIDETAIL"
ADD "APERTURA" VARCHAR2 (12) DEFAULT ('')
GO


UPDATE "TAG_DOORS_MAGGIORAZIONIDETAIL" SET "APERTURA" = '' WHERE "APERTURA" IS NULL
GO


