ALTER TABLE "TAG_DOORS_POLTELAIODETAIL"
ADD "LCF1" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_POLTELAIODETAIL" SET "LCF1" = 0 WHERE "LCF1" IS NULL
GO


ALTER TABLE "TAG_DOORS_POLTELAIODETAIL"
ADD "QYACF1" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_POLTELAIODETAIL" SET "QYACF1" = 0 WHERE "QYACF1" IS NULL
GO


