ALTER TABLE "MA_ITEMS"
ADD "DOORSAPERTURA" VARCHAR2 (12) DEFAULT ('')
GO


UPDATE "MA_ITEMS" SET "DOORSAPERTURA" = '' WHERE "DOORSAPERTURA" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSNOTE" VARCHAR2 (50) DEFAULT ('')
GO


UPDATE "MA_ITEMS" SET "DOORSNOTE" = '' WHERE "DOORSNOTE" IS NULL
GO


