ALTER TABLE "MA_SALEORDDETAILS"
ADD "DOORSLARGHEZZA" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_SALEORDDETAILS" SET "DOORSLARGHEZZA" = 0 WHERE "DOORSLARGHEZZA" IS NULL
GO


ALTER TABLE "MA_SALEORDDETAILS"
ADD "DOORSALTEZZA" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_SALEORDDETAILS" SET "DOORSALTEZZA" = 0 WHERE "DOORSALTEZZA" IS NULL
GO


ALTER TABLE "MA_SALEORDDETAILS"
ADD "DOORSSPMURO" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_SALEORDDETAILS" SET "DOORSSPMURO" = 0 WHERE "DOORSSPMURO" IS NULL
GO


