ALTER TABLE "TAG_DOORS_MAGGIORAZIONI"
ADD "SCONTO1" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_MAGGIORAZIONI" SET "SCONTO1" = 0 WHERE "SCONTO1" IS NULL
GO


ALTER TABLE "TAG_DOORS_MAGGIORAZIONI"
ADD "SCONTO2" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_MAGGIORAZIONI" SET "SCONTO2" = 0 WHERE "SCONTO2" IS NULL
GO


ALTER TABLE "TAG_DOORS_MAGGIORAZIONI"
ADD "SCONTO3" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_MAGGIORAZIONI" SET "SCONTO3" = 0 WHERE "SCONTO3" IS NULL
GO


ALTER TABLE "TAG_DOORS_MAGGIORAZIONI"
ADD "PROVVIGIONE" FLOAT (126) DEFAULT (0)
GO


UPDATE "TAG_DOORS_MAGGIORAZIONI" SET "PROVVIGIONE" = 0 WHERE "PROVVIGIONE" IS NULL
GO


