ALTER TABLE "TAG_DOORS_PARAMS"
ADD "CATMERCPORTE" VARCHAR2 (8) DEFAULT ('')
GO


UPDATE "TAG_DOORS_PARAMS" SET "CATMERCPORTE" = '' WHERE "CATMERCPORTE" IS NULL
GO


ALTER TABLE "TAG_DOORS_PARAMS"
ADD "CATMERCTELAI" VARCHAR2 (8) DEFAULT ('')
GO


UPDATE "TAG_DOORS_PARAMS" SET "CATMERCTELAI" = '' WHERE "CATMERCTELAI" IS NULL
GO


ALTER TABLE "TAG_DOORS_PARAMS"
ADD "CATMERCIMBOTTI" VARCHAR2 (8) DEFAULT ('')
GO


UPDATE "TAG_DOORS_PARAMS" SET "CATMERCIMBOTTI" = '' WHERE "CATMERCIMBOTTI" IS NULL
GO


