ALTER TABLE "MA_ITEMS"
ADD "DOORSCOEFFL" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSCOEFFL" = 0 WHERE "DOORSCOEFFL" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSCOEFFH" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSCOEFFH" = 0 WHERE "DOORSCOEFFH" IS NULL
GO


ALTER TABLE "MA_ITEMS"
ADD "DOORSCOEFFP" FLOAT (126) DEFAULT (0)
GO


UPDATE "MA_ITEMS" SET "DOORSCOEFFP" = 0 WHERE "DOORSCOEFFP" IS NULL
GO


