ALTER TABLE "TAG_DOORS_TABELLAPANNELLIR"
ADD "DIMENSIONE" NUMBER (10) DEFAULT (1543569408)
GO


UPDATE "TAG_DOORS_TABELLAPANNELLIR" SET "DIMENSIONE" = 1543569408 WHERE "DIMENSIONE" IS NULL
GO


ALTER TABLE "TAG_DOORS_TABELLAPANNELLIR"
ADD "OPERATION1" VARCHAR2 (21) DEFAULT ('')
GO


UPDATE "TAG_DOORS_TABELLAPANNELLIR" SET "OPERATION1" = '' WHERE "OPERATION1" IS NULL
GO


ALTER TABLE "TAG_DOORS_TABELLAPANNELLIR"
ADD "OPERATION2" VARCHAR2 (21) DEFAULT ('')
GO


UPDATE "TAG_DOORS_TABELLAPANNELLIR" SET "OPERATION2" = '' WHERE "OPERATION2" IS NULL
GO


ALTER TABLE "TAG_DOORS_TABELLAPANNELLIR"
ADD "OPERATION3" VARCHAR2 (21) DEFAULT ('')
GO


UPDATE "TAG_DOORS_TABELLAPANNELLIR" SET "OPERATION3" = '' WHERE "OPERATION3" IS NULL
GO


